//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace TENCENT.OSS.CFT.KF.KF_Web.BatchPay_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BatchPay_ServiceSoap", Namespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service")]
    public partial class BatchPay_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RefundOther_ShowDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRefundState_OtherOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefundOther_InitGrid_ROperationCompleted;
        
        private System.Threading.SendOrPostCallback GetZWDicValueByKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BatchPay_Service() {
            this.Url = global::TENCENT.OSS.CFT.KF.KF_Web.Properties.Settings.Default.finance_web_BatchPay_Service_BatchPay_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RefundOther_ShowDataCompletedEventHandler RefundOther_ShowDataCompleted;
        
        /// <remarks/>
        public event GetRefundState_OtherCompletedEventHandler GetRefundState_OtherCompleted;
        
        /// <remarks/>
        public event RefundOther_InitGrid_RCompletedEventHandler RefundOther_InitGrid_RCompleted;
        
        /// <remarks/>
        public event GetZWDicValueByKeyCompletedEventHandler GetZWDicValueByKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Tencent.com/OSS/C2C/Finance/BatchPay_Service/RefundOther_ShowData", RequestNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", ResponseNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RefundOther_ShowData(string strBatchID) {
            object[] results = this.Invoke("RefundOther_ShowData", new object[] {
                        strBatchID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRefundOther_ShowData(string strBatchID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RefundOther_ShowData", new object[] {
                        strBatchID}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndRefundOther_ShowData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RefundOther_ShowDataAsync(string strBatchID) {
            this.RefundOther_ShowDataAsync(strBatchID, null);
        }
        
        /// <remarks/>
        public void RefundOther_ShowDataAsync(string strBatchID, object userState) {
            if ((this.RefundOther_ShowDataOperationCompleted == null)) {
                this.RefundOther_ShowDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefundOther_ShowDataOperationCompleted);
            }
            this.InvokeAsync("RefundOther_ShowData", new object[] {
                        strBatchID}, this.RefundOther_ShowDataOperationCompleted, userState);
        }
        
        private void OnRefundOther_ShowDataOperationCompleted(object arg) {
            if ((this.RefundOther_ShowDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefundOther_ShowDataCompleted(this, new RefundOther_ShowDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Tencent.com/OSS/C2C/Finance/BatchPay_Service/GetRefundState_Other", RequestNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", ResponseNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Param[] GetRefundState_Other(string batchid) {
            object[] results = this.Invoke("GetRefundState_Other", new object[] {
                        batchid});
            return ((Param[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRefundState_Other(string batchid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRefundState_Other", new object[] {
                        batchid}, callback, asyncState);
        }
        
        /// <remarks/>
        public Param[] EndGetRefundState_Other(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Param[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRefundState_OtherAsync(string batchid) {
            this.GetRefundState_OtherAsync(batchid, null);
        }
        
        /// <remarks/>
        public void GetRefundState_OtherAsync(string batchid, object userState) {
            if ((this.GetRefundState_OtherOperationCompleted == null)) {
                this.GetRefundState_OtherOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRefundState_OtherOperationCompleted);
            }
            this.InvokeAsync("GetRefundState_Other", new object[] {
                        batchid}, this.GetRefundState_OtherOperationCompleted, userState);
        }
        
        private void OnGetRefundState_OtherOperationCompleted(object arg) {
            if ((this.GetRefundState_OtherCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRefundState_OtherCompleted(this, new GetRefundState_OtherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Tencent.com/OSS/C2C/Finance/BatchPay_Service/RefundOther_InitGrid_R", RequestNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", ResponseNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RefundOther_InitGrid_R(string beginDate, string endDate, string banktype, int status, string proposer, string refundPath) {
            object[] results = this.Invoke("RefundOther_InitGrid_R", new object[] {
                        beginDate,
                        endDate,
                        banktype,
                        status,
                        proposer,
                        refundPath});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRefundOther_InitGrid_R(string beginDate, string endDate, string banktype, int status, string proposer, string refundPath, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RefundOther_InitGrid_R", new object[] {
                        beginDate,
                        endDate,
                        banktype,
                        status,
                        proposer,
                        refundPath}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndRefundOther_InitGrid_R(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RefundOther_InitGrid_RAsync(string beginDate, string endDate, string banktype, int status, string proposer, string refundPath) {
            this.RefundOther_InitGrid_RAsync(beginDate, endDate, banktype, status, proposer, refundPath, null);
        }
        
        /// <remarks/>
        public void RefundOther_InitGrid_RAsync(string beginDate, string endDate, string banktype, int status, string proposer, string refundPath, object userState) {
            if ((this.RefundOther_InitGrid_ROperationCompleted == null)) {
                this.RefundOther_InitGrid_ROperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefundOther_InitGrid_ROperationCompleted);
            }
            this.InvokeAsync("RefundOther_InitGrid_R", new object[] {
                        beginDate,
                        endDate,
                        banktype,
                        status,
                        proposer,
                        refundPath}, this.RefundOther_InitGrid_ROperationCompleted, userState);
        }
        
        private void OnRefundOther_InitGrid_ROperationCompleted(object arg) {
            if ((this.RefundOther_InitGrid_RCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefundOther_InitGrid_RCompleted(this, new RefundOther_InitGrid_RCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Tencent.com/OSS/C2C/Finance/BatchPay_Service/GetZWDicValueByKey", RequestNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", ResponseNamespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetZWDicValueByKey(string key) {
            object[] results = this.Invoke("GetZWDicValueByKey", new object[] {
                        key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetZWDicValueByKey(string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetZWDicValueByKey", new object[] {
                        key}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetZWDicValueByKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetZWDicValueByKeyAsync(string key) {
            this.GetZWDicValueByKeyAsync(key, null);
        }
        
        /// <remarks/>
        public void GetZWDicValueByKeyAsync(string key, object userState) {
            if ((this.GetZWDicValueByKeyOperationCompleted == null)) {
                this.GetZWDicValueByKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetZWDicValueByKeyOperationCompleted);
            }
            this.InvokeAsync("GetZWDicValueByKey", new object[] {
                        key}, this.GetZWDicValueByKeyOperationCompleted, userState);
        }
        
        private void OnGetZWDicValueByKeyOperationCompleted(object arg) {
            if ((this.GetZWDicValueByKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetZWDicValueByKeyCompleted(this, new GetZWDicValueByKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Tencent.com/OSS/C2C/Finance/BatchPay_Service")]
    public partial class Param {
        
        private string paramNameField;
        
        private string paramValueField;
        
        private string paramFlagField;
        
        /// <remarks/>
        public string ParamName {
            get {
                return this.paramNameField;
            }
            set {
                this.paramNameField = value;
            }
        }
        
        /// <remarks/>
        public string ParamValue {
            get {
                return this.paramValueField;
            }
            set {
                this.paramValueField = value;
            }
        }
        
        /// <remarks/>
        public string ParamFlag {
            get {
                return this.paramFlagField;
            }
            set {
                this.paramFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RefundOther_ShowDataCompletedEventHandler(object sender, RefundOther_ShowDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefundOther_ShowDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefundOther_ShowDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetRefundState_OtherCompletedEventHandler(object sender, GetRefundState_OtherCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRefundState_OtherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRefundState_OtherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Param[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Param[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RefundOther_InitGrid_RCompletedEventHandler(object sender, RefundOther_InitGrid_RCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefundOther_InitGrid_RCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefundOther_InitGrid_RCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetZWDicValueByKeyCompletedEventHandler(object sender, GetZWDicValueByKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetZWDicValueByKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetZWDicValueByKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591