//机场三字码
var AirportCity = {
        "JIC": { name:"金昌", pinyin:"JINCHANG", abbr:"JIC", airport:"金昌机场" },
        "AYN": { name:"安阳", pinyin:"ANYANG", abbr:"AYN", airport:"安阳北郊机场" },
        "LCX": { name:"龙岩", pinyin:"LONGYAN", abbr:"LCX", airport:"龙岩冠豸山机场" },
        "LIA": { name:"梁平", pinyin:"LIANGPING", abbr:"LIA", airport:"梁平机场" },
        "NZH": { name:"满洲里", pinyin:"MANZHOULI", abbr:"MZL", airport:"满洲里呼伦贝尔机场" },
        "XNT": { name:"邢台", pinyin:"XINGTAI", abbr:"XNT", airport:"邢台褡裢机场" },
        "YIC": { name:"宜春", pinyin:"YICHUN", abbr:"YIC", airport:"宜春明月山机场" },
        "KJI": { name:"喀纳斯", pinyin:"KANASI", abbr:"KJI", airport:"喀纳斯布尔津机场" },
        "BPL": { name:"博乐", pinyin:"BOLE", abbr:"BPL", airport:"新疆博乐机场" },
        "ZQZ": { name:"张家口", pinyin:"ZHANGJIAKOU", abbr:"ZQZ", airport:"张家口宁远机场" },
        "JUH": { name:"池州", pinyin:"CHIZHOU", abbr:"CZ", airport:"九华山机场" },
        "BFJ": { name:"毕节", pinyin:"BIJIE", abbr:"BFJ", airport:"毕节飞雄机场" },
        "ERL": { name:"二连浩特", pinyin:"ERLIANHAOTE", abbr:"ERL", airport:"二连浩特赛乌苏国际机场" },
        "RLK": { name:"巴彦淖尔", pinyin:"BAYANNAOER", abbr:"RLK", airport:"巴彦淖尔机场" },
        "JGD": { name:"加格达奇", pinyin:"JIAGEDAQI", abbr:"JGD", airport:"加格达奇机场" },
        "TLQ": { name:"吐鲁番", pinyin:"TULUFAN", abbr:"TLQ", airport:"吐鲁番机场" },

        "AAT": { name:"阿勒泰", pinyin:"ALETAI", abbr:"ALT", airport:"阿勒泰机场" },
        "ACX": { name:"兴义", pinyin:"XINGYI", abbr:"XY", airport:"贵阳兴义机场" },
        "AEB": { name:"百色", pinyin:"BAISE", abbr:"BS", airport:"广西百色（田阳）机场" },
        "AKA": { name:"安康", pinyin:"ANKANG", abbr:"AK", airport:"安康机场" },
        "AKU": { name:"阿克苏", pinyin:"AKESU", abbr:"AKS", airport:"阿克苏机场" },
        "AOG": { name:"鞍山", pinyin:"ANSHAN", abbr:"AS", airport:"鞍山机场" },
        "AQG": { name:"安庆", pinyin:"ANQING", abbr:"AQ", airport:"安庆（天柱山）机场" },
        "AVA": { name:"安顺", pinyin:"ANSHUN", abbr:"AS", airport:"贵州安顺黄果树机场" },
        "BAV": { name:"包头", pinyin:"BAOTOU", abbr:"BT", airport:"包头二里半机场" },
        "BFU": { name:"蚌埠", pinyin:"BENGBU", abbr:"BB", airport:"蚌埠机场" },
        "BHY": { name:"北海", pinyin:"BEIHAI", abbr:"BH", airport:"北海福城机场" },
        "BPX": { name:"昌都", pinyin:"CHAMDO", abbr:"CD", airport:"西藏昌都邦达机场" },
        "BSD": { name:"保山", pinyin:"BAOSHAN", abbr:"BS", airport:"保山云瑞机场" },
        "CAN": { name:"广州", pinyin:"GUANGZHOU", abbr:"GZ", airport:"广州白云机场" },
        "CGD": { name:"常德", pinyin:"CHANGDE", abbr:"CD", airport:"常德桃花源（斗姆湖）机场" },
        "CGO": { name:"郑州", pinyin:"ZHENGZHOU", abbr:"ZZ", airport:"郑州新郑机场" },
        "CGQ": { name:"长春", pinyin:"CHANGCHUN", abbr:"CC", airport:"长春龙嘉国际机场" },
        "CHG": { name:"朝阳", pinyin:"CHAOYANG", abbr:"CY", airport:"辽宁朝阳机场" },
        "CHW": { name:"酒泉", pinyin:"JIUQUAN", abbr:"JQ", airport:"酒泉机场" },
        "CIF": { name:"赤峰", pinyin:"CHIFENG", abbr:"CF", airport:"赤峰玉龙机场" },
        "CIH": { name:"长治", pinyin:"CHANGZHI", abbr:"CZ", airport:"长治王村机场" },
        "CKG": { name:"重庆", pinyin:"CHONGQING", abbr:"CQ", airport:"重庆江北机场" },
        "CNI": { name:"长海", pinyin:"CHANGHAI", abbr:"CH", airport:"长海（大长山岛）机场" },
        "CSX": { name:"长沙", pinyin:"CHANGSHA", abbr:"CS", airport:"长沙黄花机场" },
        "CTU": { name:"成都", pinyin:"CHENGDU", abbr:"CD", airport:"成都双流机场" },
        "CYI": { name:"嘉义", pinyin:"JIAYI", abbr:"JYG", airport:"嘉义机场" },
        "CZX": { name:"常州", pinyin:"CHANGZHOU", abbr:"CZ", airport:"常州奔牛机场" },
        "DAT": { name:"大同", pinyin:"DATONG", abbr:"DT", airport:"山西大同机场" },
        "DAX": { name:"达州", pinyin:"DAZHOU", abbr:"DZ", airport:"达州（河市）机场" },
        "DDG": { name:"丹东", pinyin:"DANDONG", abbr:"DD", airport:"丹东浪头机场" },
        "DIG1": { name:"迪庆", pinyin:"DIQING", abbr:"DQ", airport:"迪庆香格里拉机场" },
        "DIG": { name:"香格里拉", pinyin:"XIANGGELILA", abbr:"XGLL", airport:"迪庆香格里拉机场" },
        "DLC": { name:"大连", pinyin:"DALIAN", abbr:"DL", airport:"大连周水子机场" },
        "DLU": { name:"大理", pinyin:"DALI", abbr:"DL", airport:"大理荒草坝机场" },
        "DNH": { name:"敦煌", pinyin:"DUNHUANG", abbr:"DH", airport:"敦煌机场" },
        "DOY": { name:"东营", pinyin:"DONGYING", abbr:"DY", airport:"东营永安机场" },
        "DQA": { name:"大庆", pinyin:"DAQING", abbr:"DQ", airport:"大庆萨尔图机场" },
        "DSN": { name:"鄂尔多斯", pinyin:"EERDUOSI", abbr:"EEDS", airport:"鄂尔多斯伊金霍洛机场" },
        "DYG": { name:"张家界", pinyin:"ZHANGJIAJIE", abbr:"ZJJ", airport:"张家界荷花机场" },
        "ENH": { name:"恩施", pinyin:"ENSHI", abbr:"ES", airport:"恩施机场" },
        "ENY": { name:"延安", pinyin:"YANAN", abbr:"YA", airport:"延安二十里铺机场" },
        "FOC": { name:"福州", pinyin:"FUZHOU", abbr:"FZ", airport:"福州长乐机场" },
        "FUG": { name:"阜阳", pinyin:"FUYANG", abbr:"FY", airport:"阜阳西关机场"},
        "FYN": { name:"富蕴", pinyin:"FUYUN", abbr:"FY", airport:"富蕴机场" },
        "GHN": { name:"广汉", pinyin:"GUANGHAN", abbr:"GH", airport:"广汉机场" },
        "GOQ": { name:"格尔木", pinyin:"GEERMU", abbr:"GEM", airport:"格尔木机场" },
        "HAK": { name:"海口", pinyin:"HAIKOU", abbr:"HK", airport:"海口美兰机场" },
        "HDG": { name:"邯郸", pinyin:"HANDAN", abbr:"HD", airport:"河北邯郸机场机场" },
        "HEK": { name:"黑河", pinyin:"HEIHE", abbr:"HH", airport:"黑河机场" },
        "HET": { name:"呼和浩特", pinyin:"HUHEHAOTE", abbr:"HHHT", airport:"呼和浩特白塔国际机场" },
        "HFE": { name:"合肥", pinyin:"HEFEI", abbr:"HF", airport:"合肥骆岗机场" },
        "HGH": { name:"杭州", pinyin:"HANGZHOU", abbr:"HZ", airport:"杭州萧山机场" },
        "HIA": { name:"淮安", pinyin:"HUAIAN", abbr:"HA", airport:"淮安涟水机场"},
        "HJJ": { name:"怀化", pinyin:"HUAIHUA", abbr:"HH", airport:"怀化芷江机场" },
        "HLD": { name:"海拉尔", pinyin:"HAILAER", abbr:"HLE", airport:"内蒙古海拉尔东山机场" },
        "HLH": { name:"乌兰浩特", pinyin:"WULANHAOTE", abbr:"WLHT", airport:"乌兰浩特机场" },
        "HMI": { name:"哈密", pinyin:"HAMI", abbr:"HM", airport:"哈密机场" },
        "HNY": { name:"衡阳", pinyin:"HENGYANG", abbr:"HY", airport:"衡阳东江机场" },
        "HRB": { name:"哈尔滨", pinyin:"HAERBIN", abbr:"HEB", airport:"哈尔滨太平机场" },
        "HSN": { name:"舟山", pinyin:"ZHOUSHAN", abbr:"ZS", airport:"舟山普陀山朱家尖机场" },
        "HTN": { name:"和田", pinyin:"HETIAN", abbr:"HT", airport:"和田机场" },
        "HYN": { name:"台州", pinyin:"TAIZHOU", abbr:"TZ", airport:"台州路桥（原黄岩路桥）机场" },
        "HZG": { name:"汉中", pinyin:"HANZHONG", abbr:"HZ", airport:"汉中西关机场" },
        "HZH": { name:"黎平", pinyin:"LIPING", abbr:"LP", airport:"贵州黎平机场" },
        "INC": { name:"银川", pinyin:"YINCHUAN", abbr:"YC", airport:"银川河东机场" },
        "IQM": { name:"且末", pinyin:"QIEMO", abbr:"QM", airport:"且末机场" },
        "IQN": { name:"庆阳", pinyin:"QINGYANG", abbr:"QY", airport:"庆阳机场" },
        "JDZ": { name:"景德镇", pinyin:"JINGDEZHEN", abbr:"JDZ", airport:"景德镇罗家机场" },
        "JGN": { name:"嘉峪关", pinyin:"JIAYUGUAN", abbr:"JYG", airport:"嘉峪关机场" },
        "JHG": { name:"景洪", pinyin:"JINGHONG", abbr:"JH", airport:"景洪（西双版纳）机场" },
        "JHG": { name:"西双版纳", pinyin:"XISHUANGBANNA", abbr:"XSBN", airport:"景洪（西双版纳）机场" },
        "JIL": { name:"吉林", pinyin:"JILIN", abbr:"JL", airport:"吉林二台子机场" },
        "JIU": { name:"九江", pinyin:"JIUJIANG", abbr:"JJ", airport:"九江庐山机场" },
	      "JJN": { name:"晋江", pinyin:"JINJIANG", abbr:"JJ", airport:"泉州晋江机场" },
        "JJN2": { name:"泉州", pinyin:"QUANZHOU", abbr:"QZ", airport:"泉州晋江机场" },
        "JMU": { name:"佳木斯", pinyin:"JIAMUSI", abbr:"JMS", airport:"佳木斯机场" },
        "JNG": { name:"济宁", pinyin:"JINING", abbr:"JN", airport:"济宁机场" },
        "JNZ": { name:"锦州", pinyin:"JINZHOU", abbr:"JZ", airport:"锦州小岭子机场" },
        "JUZ": { name:"衢州", pinyin:"QUZHOU", abbr:"QZ", airport:"衢州机场" },
        "JZH": { name:"九寨沟", pinyin:"JIUZHAIGOU", abbr:"JZG", airport:"九寨沟黄龙（九黄）机场" },
        "KCA": { name:"库车", pinyin:"KUCHE", abbr:"KC", airport:"库车机场" },
        "KGT": { name:"康定", pinyin:"KANGDING", abbr:"KD", airport:"康定机场" },
        "KHG": { name:"喀什", pinyin:"KASHI", abbr:"KS", airport:"喀什机场" },
        "KHH": { name:"高雄", pinyin:"GAOXIONG", abbr:"GX", airport:"高雄机场" },
        "KHN": { name:"南昌", pinyin:"NANCHANG", abbr:"NC", airport:"南昌昌北机场" },
        "KJI": { name:"喀纳斯", pinyin:"KANASI", abbr:"KJI", airport:"喀纳斯布尔津机场" },
        "KMG": { name:"昆明", pinyin:"KUNMING", abbr:"KM", airport:"昆明长水国际机场" },
        "KOW": { name:"赣州", pinyin:"GANZHOU", abbr:"GZ", airport:"赣州黄金机场" },
        "KRK": { name:"克拉科夫", pinyin:"KELAKEFU", abbr:"KLKF", airport:"克拉科夫机场" },
        "KRL": { name:"库尔勒", pinyin:"KUERLE", abbr:"KEL", airport:"库尔勒机场" },
        "KRY": { name:"克拉玛依", pinyin:"KELAMAYI", abbr:"KLMY", airport:"克拉玛依机场" },
        "KWE": { name:"贵阳", pinyin:"GUIYANG", abbr:"GY", airport:"贵阳龙洞堡机场" },
        "KWL": { name:"桂林", pinyin:"GUILIN", abbr:"GL", airport:"桂林两江机场" },
        "LDS": { name:"伊春", pinyin:"YICHUN", abbr:"YC", airport:"伊春林都机场"},
        "LHW": { name:"兰州", pinyin:"LANZHOU", abbr:"LZ", airport:"兰州机场" },
        "LJG": { name:"丽江", pinyin:"LIJIANG", abbr:"LJ", airport:"丽江三义机场" },
        "LLB": { name:"荔波", pinyin:"LIBO", abbr:"LB", airport:"荔波机场" },
        "LLF": { name:"永州", pinyin:"YONGZHOU", abbr:"YZ", airport:"永州零陵机场"},
        "LNJ": { name:"临沧", pinyin:"LINCANG", abbr:"LC", airport:"临沧机场" },
        "LUM": { name:"芒市", pinyin:"MANGSHI", abbr:"MS", airport:"芒市机场" },
        "LXA": { name:"拉萨", pinyin:"LASA", abbr:"LS", airport:"拉萨贡嘎机场" },
        "LYA": { name:"洛阳", pinyin:"LUOYANG", abbr:"LY", airport:"洛阳机场" },
        "LYG": { name:"连云港", pinyin:"LIANYUNGANG", abbr:"LYG", airport:"连云港白塔埠机场" },
        "LYI": { name:"临沂", pinyin:"LINYI", abbr:"LY", airport:"临沂沭埠岭机场" },
        "LZH": { name:"柳州", pinyin:"LIUZHOU", abbr:"LZ", airport:"柳州白莲机场" },
        "LZO": { name:"泸州", pinyin:"LUZHOU", abbr:"LZ", airport:"泸州蓝田机场" },
        "LZY": { name:"林芝", pinyin:"LINZHI", abbr:"LZ", airport:"林芝机场" },
        "MDG": { name:"牡丹江", pinyin:"MUDANJIANG", abbr:"MDJ", airport:"牡丹江海浪机场" },
        "MIG": { name:"绵阳", pinyin:"MIANYANG", abbr:"MY", airport:"绵阳南郊机场" },
        "MXZ": { name:"梅县", pinyin:"MEIXIAN", abbr:"MX", airport:"梅县机场" },
        "NAO": { name:"南充", pinyin:"NANCHONG", abbr:"NC", airport:"南充高坪机场" },
        "NAY": { name:"北京南苑", pinyin:"BEIJING", abbr:"BJNW", airport:"北京南苑机场" },
        "NBS": { name:"长白山", pinyin:"CHANGBAISHAN", abbr:"CBS", airport:"长白山机场" },
        "NDG": { name:"齐齐哈尔", pinyin:"QIQIHAER", abbr:"QQHE", airport:"齐齐哈尔三家子机场" },
        "NGB": { name:"宁波", pinyin:"NINGBO", abbr:"NB", airport:"宁波栎社机场" },
        "NKG": { name:"南京", pinyin:"NANJING", abbr:"NJ", airport:"南京禄口机场" },
        "NLT": { name:"那拉提", pinyin:"NALATI", abbr:"NLT", airport:"那拉提机场" },
        "NNG": { name:"南宁", pinyin:"NANNING", abbr:"NN", airport:"南宁吴圩机场" },
        "NNY": { name:"南阳", pinyin:"NANYANG", abbr:"NY", airport:"南阳姜营机场" },
        "NTG": { name:"南通", pinyin:"NANTONG", abbr:"NT", airport:"南通兴东机场" },
        "NZH": { name:"满洲里", pinyin:"MANZHOULI", abbr:"MZL", airport:"呼伦贝尔满洲里西郊机场" },
        "OHE": { name:"漠河", pinyin:"MOHE", abbr:"MH", airport:"漠河古莲机场" },
        "PEK": { name:"北京", pinyin:"BEIJING", abbr:"BJ", airport:"北京首都机场" },
        "PVG": { name:"上海浦东", pinyin:"SHANGHAI", abbr:"SH", airport:"上海浦东机场" },
        "PZI": { name:"攀枝花", pinyin:"PANZHIHUA", abbr:"PZH", airport:"攀枝花保安营机场" },
        "SHA": { name:"上海虹桥", pinyin:"SHANGHAI", abbr:"SH", airport:"上海虹桥机场" },
        "SHE": { name:"沈阳", pinyin:"SHENYANG", abbr:"SY", airport:"沈阳桃仙机场" },
        "SHP": { name:"秦皇岛", pinyin:"QINHUANGDAO", abbr:"QHD", airport:"秦皇岛山海关机场" },
        "SHS": { name:"荆州", pinyin:"JINGZHOU", abbr:"JZ",airport:"荆州沙市机场"},
        "SHS": { name:"沙市", pinyin:"SHASHI", abbr:"SS", airport:"荆州沙市机场" },
        "SJW": { name:"石家庄", pinyin:"SHIJIAZHUANG", abbr:"SJZ", airport:"石家庄正定机场" },
        "SWA": { name:"揭阳", pinyin:"JIEYANG", abbr:"JY", airport:"揭阳潮汕机场" },
        "SYM": { name:"普洱", pinyin:"PUER", abbr:"PE", airport:"普洱（思茅）机场" },
        "SYX": { name:"三亚", pinyin:"SANYA", abbr:"SY", airport:"三亚凤凰机场" },
        "SZV": { name:"苏州", pinyin:"SUZHOU", abbr:"SZ", airport:"苏州机场" },
        "SZX": { name:"深圳", pinyin:"SHENZHEN", abbr:"SZ", airport:"深圳宝安机场" },
        "TAO": { name:"青岛", pinyin:"QINGDAO", abbr:"QD", airport:"青岛流亭机场" },
        "TCG": { name:"塔城", pinyin:"TACHENG", abbr:"TC", airport:"塔城机场" },
        "TCZ": { name:"腾冲", pinyin:"TENGCHONG", abbr:"TC", airport:"腾冲（驼峰）机场" },
        "TEN": { name:"铜仁", pinyin:"TONGREN", abbr:"TR", airport:"铜仁凤凰机场" },
        "TGO": { name:"通辽", pinyin:"TONGLIAO", abbr:"TL", airport:"通辽机场" },
        "THQ": { name:"天水", pinyin:"TIANSHUI", abbr:"TS", airport:"甘肃天水机场" },
        "TNA": { name:"济南", pinyin:"JINAN", abbr:"JN", airport:"济南遥墙机场" },
        "TNH": { name:"通化", pinyin:"TONGHUA", abbr:"TH", airport:"通化机场" },
        "TSN": { name:"天津", pinyin:"TIANJIN", abbr:"TJ", airport:"天津滨海机场" },
        "TVS": { name:"唐山", pinyin:"TANGSHAN", abbr:"TS", airport:"唐山三女河机场" },
        "TXN": { name:"黄山", pinyin:"HUANGSHAN", abbr:"HS", airport:"黄山屯溪机场" },
        "TYN": { name:"太原", pinyin:"TAIYUAN", abbr:"TY", airport:"太原武宿机场" },
        "URC": { name:"乌鲁木齐", pinyin:"WULUMUQI", abbr:"WLMQ", airport:"乌鲁木齐地窝堡机场" },
        "UYN": { name:"榆林", pinyin:"YULIN", abbr:"YL", airport:"榆林西沙机场" },
        "WEF": { name:"潍坊", pinyin:"WEIFANG", abbr:"WF", airport:"潍坊机场" },
        "WEH": { name:"威海", pinyin:"WEIHAI", abbr:"WH", airport:"威海文登大水泊机场" },
        "WNH": { name:"文山", pinyin:"WENSHAN", abbr:"WS", airport:"云南文山普者黑机场" },
        "WNZ": { name:"温州", pinyin:"WENZHOU", abbr:"WZ", airport:"温州永强机场" },
        "WUA": { name:"乌海", pinyin:"WUHAI", abbr:"WH", airport:"乌海机场" },
        "WUH": { name:"武汉", pinyin:"WUHAN", abbr:"WH", airport:"武汉天河机场" },
        "WUS": { name:"武夷山", pinyin:"WUYISHAN", abbr:"WYS", airport:"武夷山机场" },
        "WUX": { name:"无锡", pinyin:"WUXI", abbr:"WX", airport:"无锡硕放机场" },
        "WUZ": { name:"梧州", pinyin:"WUZHOU", abbr:"WZ", airport:"广西梧州长洲岛机场" },
        "WXN": { name:"万州", pinyin:"WANZHOU", abbr:"WZ", airport:"重庆万州机场" },
        "XFN": { name:"襄阳", pinyin:"XIANGYANG", abbr:"XY", airport:"襄阳刘集机场" },
        "XIC": { name:"西昌", pinyin:"XICHANG", abbr:"XC", airport:"西昌青山机场" },
        "XIL": { name:"锡林浩特", pinyin:"XILINHAOTE", abbr:"XLHT", airport:"锡林浩特机场" },
        "XIY": { name:"西安", pinyin:"XIAN", abbr:"XA", airport:"西安咸阳机场" },
        "SIA": { name:"西安", pinyin:"XIAN", abbr:"XA", airport:"西安咸阳机场" },//西安特殊处理,传过去的参数必须为SIA,但查询后返回的报文中的机场信息却为XIY(只针对于南航)
        "XMN": { name:"厦门", pinyin:"XIAMEN", abbr:"XM", airport:"厦门高崎机场" },
        "XNN": { name:"西宁", pinyin:"XINING", abbr:"XN", airport:"西宁曹家堡机场" },
        "XUZ": { name:"徐州", pinyin:"XUZHOU", abbr:"XZ", airport:"徐州观音机场" },
        "YBP": { name:"宜宾", pinyin:"YIBIN", abbr:"YB", airport:"宜宾（菜坝）机场" },
        "YCU": { name:"运城", pinyin:"YUNCHENG", abbr:"YC", airport:"运城关公机场" },
        "YIH": { name:"宜昌", pinyin:"YICHANG", abbr:"YC", airport:"宜昌三峡机场" },
        "YIN": { name:"伊宁", pinyin:"YINING", abbr:"YN", airport:"伊宁机场" },
        "YIW": { name:"义乌", pinyin:"YIWU", abbr:"YW", airport:"义乌机场" },
        "YNJ": { name:"延吉", pinyin:"YANJI", abbr:"YJ", airport:"延吉朝阳川机场" },
        "YNT": { name:"烟台", pinyin:"YANTAI", abbr:"YT", airport:"烟台莱山机场" },
        "YNZ": { name:"盐城", pinyin:"YANCHENG", abbr:"YC", airport:"江苏盐城南洋机场" },
        "YUS": { name:"玉树", pinyin:"YUSHU", abbr:"YS", airport:"青海玉树三江源（巴塘）机场" },
        "ZAT": { name:"昭通", pinyin:"ZHAOTONG", abbr:"ZT", airport:"昭通机场" },
        "ZHA": { name:"湛江", pinyin:"ZHANJIANG", abbr:"ZJ", airport:"湛江机场" },
        "ZHY": { name:"中卫", pinyin:"ZHONGWEI", abbr:"ZW", airport:"中卫（香山、沙坡头）机场" },
        "ZUH": { name:"珠海", pinyin:"ZHUHAI", abbr:"ZH", airport:"珠海三灶机场" },
        "JGS": { name:"井冈山", pinyin:"JINGGANGSHAN", abbr:"JGS", airport:"井冈山机场" },
        "GYS": { name:"广元", pinyin:"GUANGYUAN", abbr:"GY", airport:"广元机场" },
        "JXA": { name:"鸡西", pinyin:"JIXI", abbr:"JX", airport:"鸡西机场" },
        "ZYI": { name:"遵义", pinyin:"ZUNYI", abbr:"ZY", airport:"遵义机场" },

        "ADD":{name:"亚的斯亚贝巴",gj:"gj",airport:"亚的斯亚贝巴机场"},
        "JNB":{name:"约翰内斯堡",gj:"gj",airport:"约翰内斯堡机场"},
        "LAD":{name:"罗安达",gj:"gj",airport:"罗安达二月四日机场"},
        "NBO":{name:"内罗毕",gj:"gj",airport:"内罗毕乔莫·肯雅塔机场"},
        "TNR":{name:"安塔那那利佛",gj:"gj",airport:"安塔那那利佛国际机场"},
        "ADL":{name:"阿德莱德",gj:"gj",airport:"阿德莱德机场"},
        "AKL":{name:"奥克兰",gj:"gj",airport:"奥克兰机场"},
        "BNE":{name:"布里斯班",gj:"gj",airport:"布里斯班机场"},
        "CHC":{name:"基督城",gj:"gj",airport:"基督城机场"},
        "CNS":{name:"凯恩斯",gj:"gj",airport:"凯恩斯机场"},
        "AVV":{name:"墨尔本",gj:"gj",airport:"爱华隆机场"},
        "KAH":{name:"墨尔本",gj:"gj",airport:"墨尔本机场"},
        "MEB":{name:"墨尔本",gj:"gj",airport:"墨尔本机场"},
        "MEL":{name:"墨尔本 ",gj:"gj",airport:"墨尔本机场"},
        "NAN":{name:"南迪",gj:"gj",airport:"南迪机场"},
        "OOL":{name:"黄金海岸",gj:"gj",airport:"黄金海岸机场"},
        "SYD":{name:"悉尼",gj:"gj",airport:"悉尼金斯福德·史密斯机场"},
        "AMS":{name:"阿姆斯特丹",gj:"gj",airport:"荷兰阿姆斯特丹斯史基浦(西霍普)机场"},
        "BCN":{name:"巴塞罗那",gj:"gj",airport:"巴塞罗那机场"},
        "BHX":{name:"伯明翰",gj:"gj",airport:"伯明翰机场"},
        "BRU":{name:"布鲁塞尔",gj:"gj",airport:"布鲁塞尔机场"},
        "ZYR":{name:"布鲁塞尔",gj:"gj",airport:"布鲁塞尔铁路客运站"},
        "BUD":{name:"布达佩斯",gj:"gj",airport:"布达佩斯机场"},
        "CPH":{name:"哥本哈根",gj:"gj",airport:"哥本哈根机场"},
        "DUB":{name:"都柏林",gj:"gj",airport:"都柏林机场"},
        "DUS":{name:"杜塞尔多夫",gj:"gj",airport:"杜塞尔多夫机场"},
        "FRA":{name:"法兰克福",gj:"gj",airport:"法兰克福机场"},
        "GVA":{name:"日内瓦",gj:"gj",airport:"日内瓦机场"},
        "HEL":{name:"赫尔辛基",gj:"gj",airport:"赫尔辛基机场"},
        "LED":{name:"圣彼得堡",gj:"gj",airport:"圣彼得堡机场"},
        "LIS":{name:"里斯本",gj:"gj",airport:"里斯本机场"},
        "LCY":{name:"伦敦",gj:"gj",airport:"伦敦城市机场"},
        "LGW":{name:"伦敦",gj:"gj",airport:"盖特威克机场"},
        "LHR":{name:"伦敦",gj:"gj",airport:"伦敦希思罗机场"},
        "LPA":{name:"加那利群岛",gj:"gj",airport:"大加那利机场"},
        "MAD":{name:"马德里",gj:"gj",airport:"马德里机场"},
        "LIN":{name:"米兰",gj:"gj",airport:"米兰利纳特机场"},
        "MXP":{name:"米兰",gj:"gj",airport:"米兰马尔本萨机场"},
        "DME":{name:"莫斯科",gj:"gj",airport:"多莫杰多沃机场"},
        "SVO":{name:"莫斯科",gj:"gj",airport:"谢诺梅杰沃机场"},
        "MUC":{name:"慕尼黑",gj:"gj",airport:"慕尼黑机场"},
        "OVB":{name:"新西伯利亚",gj:"gj",airport:"新西伯利亚机场"},
        "CDG":{name:"巴黎",gj:"gj",airport:"戴高乐机场"},
        "ORY":{name:"巴黎",gj:"gj",airport:"巴黎－奥利机场"},
        "FCO":{name:"罗马",gj:"gj",airport:"菲乌米奇诺机场"},
        "ARN":{name:"斯德哥尔摩",gj:"gj",airport:"斯德哥尔摩机场"},
        "SVX":{name:"叶卡捷琳堡",gj:"gj",airport:"叶卡捷琳堡/科利佐沃机场机场"},
        "IKA":{name:"德黑兰",gj:"gj",airport:"伊玛目霍梅尼机场"},
        "TLS":{name:"图卢兹",gj:"gj",airport:"图卢兹布拉尼亚克机场"},
        "VIE":{name:"维也纳",gj:"gj",airport:"维也纳机场"},
        "VLC":{name:"瓦伦西亚",gj:"gj",airport:"瓦伦西亚国际机场"},
        "VVO":{name:"符拉迪沃斯托克",gj:"gj",airport:"符拉迪沃斯托克机场"},
        "ZRH":{name:"苏黎世",gj:"gj",airport:"苏黎世机场"},
        "ABE":{name:"阿伦敦",gj:"gj",airport:"阿伦敦机场"},
        "ALB":{name:"纽约",gj:"gj",airport:"奥尔巴尼机场"},
        "ATL":{name:"亚特兰大",gj:"gj",airport:"亚特兰大机场"},
        "BOS":{name:"波士顿",gj:"gj",airport:"波士顿机场"},
        "MDW":{name:"芝加哥",gj:"gj",airport:"芝加哥中途机场"},
        "ORD":{name:"芝加哥",gj:"gj",airport:"芝加哥机场"},
        "CLE":{name:"克利夫兰",gj:"gj",airport:"Cleveland Hopkins机场"},
        "CMH":{name:"哥伦布",gj:"gj",airport:"PORT COLUMBUS INTERNATIONAL AIRPORT"},
        "CVG":{name:"辛辛那提",gj:"gj",airport:"辛辛那提机场"},
        "DEN":{name:"丹佛",gj:"gj",airport:"丹佛机场"},
        "DFW":{name:"达拉斯",gj:"gj",airport:"达拉斯沃尔斯堡机场"},
        "EWR":{name:"纽瓦克",gj:"gj",airport:"纽瓦克机场"},
        "HNL":{name:"檀香山",gj:"gj",airport:"檀香山机场"},
        "LAX":{name:"洛杉矶",gj:"gj",airport:"洛杉矶机场"},
        "LEX":{name:"列克星敦",gj:"gj",airport:"列克星敦机场"},
        "JFK":{name:"纽约",gj:"gj",airport:"肯尼迪机场"},
        "LGA":{name:"纽约",gj:"gj",airport:"拉瓜迪亚机场"},
        "ORF":{name:"诺福克",gj:"gj",airport:"诺福克国际机场"},
        "SEA":{name:"西雅图",gj:"gj",airport:"西雅图机场"},
        "SFO":{name:"旧金山",gj:"gj",airport:"旧金山机场"},
        "IAD":{name:"华盛顿",gj:"gj",airport:"华盛顿杜勒斯机场"},
        "YLW":{name:"基劳纳",gj:"gj",airport:"基劳纳机场"},
        "YOW":{name:"渥太华",gj:"gj",airport:"渥太华机场"},
        "YTZ":{name:"多伦多",gj:"gj",airport:"多伦多市中心机场"},
        "YVR":{name:"温哥华",gj:"gj",airport:"温哥华机场"},
        "YWG":{name:"温尼伯",gj:"gj",airport:"温尼伯机场"},
        "YXE":{name:"萨斯卡通",gj:"gj",airport:"萨斯卡通约翰·乔治·迪芬贝克机场"},
        "YXU":{name:"安大略",gj:"gj",airport:"加拿大伦敦机场"},
        "YYC":{name:"卡尔加里",gj:"gj",airport:"CALGARY机场"},
        "YYT":{name:"圣约翰斯",gj:"gj",airport:"圣约翰斯机场"},
        "YYZ":{name:"多伦多",gj:"gj",airport:"多伦多皮尔逊机场"},
        "BSB":{name:"巴西利亚",gj:"gj",airport:"巴西利亚机场"},
        "GUM":{name:"关岛",gj:"gj",airport:"关岛机场"},
        "CGH":{name:"圣保罗",gj:"gj",airport:"圣保罗孔戈尼亚斯机场"},
        "GRU":{name:"圣保罗",gj:"gj",airport:"圣保罗机场"},
        "ALA":{name:"阿拉木图",gj:"gj",airport:"阿拉木图机场"},
        "AMM":{name:"安曼",gj:"gj",airport:"安曼阿莉娅王后机场"},
        "ESB":{name:"安卡拉",gj:"gj",airport:"安卡拉埃森博阿机场"},
        "AUH":{name:"阿布扎比",gj:"gj",airport:"阿布扎比机场"},
        "BAH":{name:"巴林",gj:"gj",airport:"巴林机场"},
        "BKK":{name:"曼谷",gj:"gj",airport:"曼谷(素万那普)机场"},
        "BWN":{name:"斯里巴加湾",gj:"gj",airport:"文莱机场"},
        "CEB":{name:"宿雾",gj:"gj",airport:"宿雾机场"},
        "CJU":{name:"济州岛",gj:"gj",airport:"济州机场"},
        "DAC":{name:"达卡",gj:"gj",airport:"齐亚机场"},
        "DEL":{name:"新德里",gj:"gj",airport:"德里机场"},
        "DOH":{name:"多哈",gj:"gj",airport:"多哈机场"},
        "DPS":{name:"登巴萨",gj:"gj",airport:"巴厘岛机场"},
        "DXB":{name:"迪拜",gj:"gj",airport:"迪拜机场"},
        "XNB":{name:"迪拜",gj:"gj",airport:"迪拜机场"},
        "XMB":{name:"迪拜",gj:"gj",airport:"迪拜铁路客运站"},
        "FUK":{name:"福冈",gj:"gj",airport:"福冈机场"},
        "HAN":{name:"河内",gj:"gj",airport:"河内机场"},
        "HKG":{name:"香港",gj:"gj",airport:"HONG KONG INTERNATIONAL AIRPORT"},
        "HKT":{name:"普吉岛",gj:"gj",airport:"普吉机场"},
        "KBP":{name:"基辅",gj:"gj",airport:"波里斯珀尔机场"},
        "ISB":{name:"伊斯兰堡",gj:"gj",airport:"伊斯兰堡机场"},
        "IST":{name:"伊斯坦布尔",gj:"gj",airport:"阿塔图尔克机场"},
        "CGK":{name:"雅加达",gj:"gj",airport:"雅加达 苏加诺-哈达机场"},
        "KTM":{name:"加德满都",gj:"gj",airport:"加德满都机场"},
        "KUL":{name:"吉隆坡",gj:"gj",airport:"吉隆坡机场"},
        "LGK":{name:"兰卡威",gj:"gj",airport:"浮罗交怡机场"},
        "MFM":{name:"澳门",gj:"gj",airport:"MACAU AIRPORT"},
        "MNL":{name:"马尼拉",gj:"gj",airport:"马尼拉机场"},
        "NGO":{name:"名古屋",gj:"gj",airport:"名古屋中部/新特丽亚机场"},
        "OKJ":{name:"冈山",gj:"gj",airport:"冈山机场"},
        "PUS":{name:"釜山",gj:"gj",airport:"金海机场"},
        "RUH":{name:"利雅德",gj:"gj",airport:"哈立德国王机场"},
        "GMP":{name:"首尔金浦",gj:"gj",airport:"首尔金浦国际机场"},
        "ICN":{name:"首尔仁川",gj:"gj",airport:"首尔仁川机场"},
        "SGN":{name:"胡志明市",gj:"gj",airport:"胡志明市机场"},
        "SIN":{name:"新加坡",gj:"gj",airport:"樟宜机场"},
        "CTS":{name:"千岁",gj:"gj",airport:"千岁机场"},
        "SPN":{name:"塞班",gj:"gj",airport:"塞班机场"},
        "TAE":{name:"大邱",gj:"gj",airport:"大邱机场"},
        "TLV":{name:"特拉维夫",gj:"gj",airport:"特拉维夫机场"},
        "TPE":{name:"桃园",gj:"gj",airport:"桃园/桃園(原中正)机场"},
        "TSA":{name:"台北",gj:"gj",airport:"台北松山机场"},
        "HND":{name:"东京羽田",gj:"gj",airport:"东京羽田国际机场"},
        "NRT":{name:"东京成田",gj:"gj",airport:"东京成田机场"},
        "ABJ":{name:"阿比让",gj:"gj",airport:"阿比让机场"},
        "ACC":{name:"阿克拉",gj:"gj",airport:"科托卡机场"},
        "AGA":{name:"阿加迪尔",gj:"gj",airport:"阿加迪尔"},
        "ALG":{name:"阿尔及尔",gj:"gj",airport:"阿尔及尔机场"},
        "ASM":{name:"阿斯马拉",gj:"gj",airport:"阿斯马拉"},
        "BGF":{name:"班吉",gj:"gj",airport:"班吉"},
        "BJL":{name:"班珠尔",gj:"gj",airport:"班珠尔"},
        "BJM":{name:"布琼布拉",gj:"gj",airport:"布琼布拉"},
        "BKO":{name:"巴马科",gj:"gj",airport:"巴马科"},
        "BOG":{name:"波哥大",gj:"gj",airport:"波哥大机场"},
        "BZV":{name:"布拉柴维尔",gj:"gj",airport:"布拉柴维尔马亚机场"},
        "CAS":{name:"卡萨布兰卡",gj:"gj",airport:"卡萨布兰卡"},
        "CMN":{name:"卡萨布兰卡",gj:"gj",airport:"默罕默德V机场"},
        "CKY":{name:"科纳克里",gj:"gj",airport:"科纳克里"},
        "COO":{name:"科托努",gj:"gj",airport:"科托努机场"},
        "CPT":{name:"开普敦",gj:"gj",airport:"开普顿机场"},
        "DAR":{name:"达累斯萨拉姆",gj:"gj",airport:"尼雷尔机场"},
        "DKR":{name:"达喀尔",gj:"gj",airport:"达喀尔机场"},
        "DLA":{name:"杜阿拉",gj:"gj",airport:"杜阿拉机场"},
        "EBB":{name:"恩德培",gj:"gj",airport:"恩德培机场"},
        "FIH":{name:"金沙萨",gj:"gj",airport:"金沙萨恩吉利机场"},
        "NLO":{name:"金萨沙",gj:"gj",airport:"Kinshasa N'Dolo Apt"},
        "FNA":{name:"弗里敦",gj:"gj",airport:"弗里敦机场"},
        "HGS":{name:"佛里敦",gj:"gj",airport:"Freetown Hastings Apt"},
        "JMY":{name:"佛里敦",gj:"gj",airport:"Freetown Mammy Yoko Heliport"},
        "GBE":{name:"哈博罗内",gj:"gj",airport:"哈博罗内"},
        "HRE":{name:"哈拉雷",gj:"gj",airport:"哈拉雷机场"},
        "JIB":{name:"吉布提市",gj:"gj",airport:"吉布提市"},
        "JRO":{name:"乞力马扎罗",gj:"gj",airport:"乞力马扎罗机场"},
        "KGL":{name:"基加利",gj:"gj",airport:"基加利"},
        "KLA":{name:"坎帕拉",gj:"gj",airport:"坎帕拉"},
        "LBV":{name:"利伯维尔",gj:"gj",airport:"利伯维尔莱昂姆巴机场"},
        "LFW":{name:"洛美",gj:"gj",airport:"纳辛贝·埃亚德马机场"},
        "LLW":{name:"利朗格韦",gj:"gj",airport:"利朗格韦"},
        "LOS":{name:"拉各斯",gj:"gj",airport:"拉各斯机场"},
        "LUN":{name:"卢萨卡",gj:"gj",airport:"卢萨卡机场"},
        "MGQ":{name:"摩加迪沙",gj:"gj",airport:"摩加迪沙"},
        "MLW":{name:"蒙罗维亚",gj:"gj",airport:"蒙罗维亚"},
        "ROB":{name:"蒙罗维亚",gj:"gj",airport:"MONROVIA ROBERTS"},
        "MPM":{name:"马普托",gj:"gj",airport:"马普托机场"},
        "MSU":{name:"马塞卢",gj:"gj",airport:"马塞卢"},
        "NDJ":{name:"恩贾梅纳",gj:"gj",airport:"恩贾梅纳"},
        "NKC":{name:"努瓦克肖特",gj:"gj",airport:"努瓦克肖特"},
        "OUA":{name:"瓦加杜古",gj:"gj",airport:"瓦加杜古机场"},
        "OXB":{name:"比绍",gj:"gj",airport:"BISSAU"},
        "HIC":{name:"比勒陀利亚",gj:"gj",airport:"Pretoria Iscor H/P"},
        "HPR":{name:"比勒陀利亚",gj:"gj",airport:"Pretoria Central H/P"},
        "PRY":{name:"比勒陀利亚",gj:"gj",airport:"比勒陀利亚"},
        "QMN":{name:"姆巴巴内",gj:"gj",airport:"Mbabane Off-Line Pt"},
        "RAI":{name:"普拉亚",gj:"gj",airport:"普拉亚"},
        "RAK":{name:"马拉喀什",gj:"gj",airport:"马拉喀什"},
        "RBA":{name:"拉巴特",gj:"gj",airport:"拉巴特机场"},
        "TIA":{name:"地拉那",gj:"gj",airport:"地拉那"},
        "TIP":{name:"的黎波里",gj:"gj",airport:"的黎波里"},
        "TMS":{name:"圣多美",gj:"gj",airport:"圣多美岛"},
        "TUN":{name:"突尼斯",gj:"gj",airport:"突尼斯机场"},
        "ERS":{name:"温得和克",gj:"gj",airport:"WINDHOEK EROS APT"},
        "WDH":{name:"温得和克",gj:"gj",airport:"温得和克卢格哈威机场"},
        "ZWH":{name:"温得和克",gj:"gj",airport:"Windhoek Rail Station"},
        "NSI":{name:"雅温得",gj:"gj",airport:"NSI MAIEN"},
        "YAO":{name:"雅温得",gj:"gj",airport:"雅温得"},
        "ASG":{name:"阿什伯顿",gj:"gj",airport:"阿什伯顿"},
        "CBR":{name:"堪培拉",gj:"gj",airport:"堪培拉机场"},
        "DRW":{name:"达尔文",gj:"gj",airport:"达尔文机场"},
        "PER":{name:"珀斯",gj:"gj",airport:"珀斯机场"},
        "SUV":{name:"苏瓦",gj:"gj",airport:"苏瓦那机场"},
        "WLG":{name:"惠灵顿",gj:"gj",airport:"惠灵顿机场"},
        "AAL":{name:"奥尔堡",gj:"gj",airport:"奥尔堡"},
        "ZTG":{name:"奥尔堡",gj:"gj",airport:"Aalborg Rail Station"},
        "ABZ":{name:"岱斯",gj:"gj",airport:"阿伯丁机场"},
        "ACI":{name:"奥尔德尼",gj:"gj",airport:"奥尔德尼机场"},
        "AGH":{name:"赫尔辛堡",gj:"gj",airport:"赫尔辛堡"},
        "JHE":{name:"赫尔辛堡",gj:"gj",airport:"HELSINGBORG H P"},
        "AGP":{name:"马拉加",gj:"gj",airport:"马拉加机场"},
        "ALC":{name:"阿利坎特",gj:"gj",airport:"阿利坎特"},
        "ALF":{name:"阿尔塔",gj:"gj",airport:"阿尔塔"},
        "ALV":{name:"安道尔",gj:"gj",airport:"Andorra la Vella"},
        "ANR":{name:"安特卫普",gj:"gj",airport:"安特卫普机场"},
        "ZAY":{name:"安特卫普",gj:"gj",airport:"ANTWERP"},
        "ZYZ":{name:"安特卫普",gj:"gj",airport:"Antwerp Berchem Rail Station"},
        "ANX":{name:"安德内斯",gj:"gj",airport:"安德内斯"},
        "ATH":{name:"雅典",gj:"gj",airport:"雅典机场"},
        "BDA":{name:"百慕大哈密尔敦",gj:"gj",airport:"百慕大哈密尔顿"},
        "NWU":{name:"百慕大哈密尔敦",gj:"gj",airport:"Bermuda NAS"},
        "BEG":{name:"贝尔格莱德",gj:"gj",airport:"贝尔格莱德"},
        "BFS":{name:"贝尔法斯特",gj:"gj",airport:"贝尔法斯特"},
        "BHD":{name:"贝尔法斯特",gj:"gj",airport:"乔治·贝斯特贝尔法斯特机场"},
        "BIO":{name:"毕尔巴鄂",gj:"gj",airport:"毕尔巴鄂机场"},
        "BOD":{name:"波尔多",gj:"gj",airport:"波尔多"},
        "ZFQ":{name:"波尔多",gj:"gj",airport:"Bordeaux Rail Station"},
        "BRE":{name:"不来梅",gj:"gj",airport:"不来梅机场"},
        "BRN":{name:"伯尔尼",gj:"gj",airport:"伯尔尼机场"},
        "ZDJ":{name:"伯尔尼",gj:"gj",airport:"Berne Rail Station"},
        "BRV":{name:"不来梅港",gj:"gj",airport:"不来梅港"},
        "BTS":{name:"布拉迪斯拉发",gj:"gj",airport:"布拉迪斯拉发"},
        "ZRG":{name:"布拉迪斯拉发",gj:"gj",airport:"BRATISLAVA"},
        "BBU":{name:"布加勒斯特",gj:"gj",airport:"CITY IN ROMANIA"},
        "OTP":{name:"布加勒斯特",gj:"gj",airport:"布加勒斯特奥托佩尼机场"},
        "CBG":{name:"剑桥",gj:"gj",airport:"剑桥"},
        "CEQ":{name:"嘎纳",gj:"gj",airport:"戛纳"},
        "JCA":{name:"嘎纳",gj:"gj",airport:"CNNES"},
        "QYW":{name:"嘎纳",gj:"gj",airport:"Cannes Vieux Port Ferry"},
        "BNJ":{name:"科隆",gj:"gj",airport:"波恩"},
        "CGN":{name:"科隆",gj:"gj",airport:"科隆机场"},
        "QKL":{name:"科隆",gj:"gj",airport:"COLOGNE MAIN STAT"},
        "QKU":{name:"科隆",gj:"gj",airport:"Cologne Deutz Rail Station"},
        "DRS":{name:"德累斯顿",gj:"gj",airport:"德累斯顿机场"},
        "EDI":{name:"爱丁堡",gj:"gj",airport:"爱丁堡机场"},
        "FAO":{name:"法鲁",gj:"gj",airport:"法鲁"},
        "FLR":{name:"佛罗伦萨",gj:"gj",airport:"佛罗伦萨机场"},
        "PSA":{name:"佛罗伦萨",gj:"gj",airport:"比萨"},
        "ZMS":{name:"佛罗伦萨",gj:"gj",airport:"FLORENCE SM RAIL"},
        "FNC":{name:"马德拉群岛",gj:"gj",airport:"丰沙尔"},
        "FRL":{name:"弗利",gj:"gj",airport:"弗利"},
        "GIB":{name:"直布罗陀",gj:"gj",airport:"直布罗陀"},
        "GLA":{name:"格拉斯哥",gj:"gj",airport:"格拉斯哥机场"},
        "PIK":{name:"格拉斯哥",gj:"gj",airport:"普雷斯蒂克机场"},
        "ZGG":{name:"格拉斯哥",gj:"gj",airport:"兰州/中川"},
        "GOA":{name:"热那亚",gj:"gj",airport:"热那亚—西塞斯特里克里斯托弗·哥伦布机场"},
        "GOJ":{name:"下诺夫哥罗德",gj:"gj",airport:"下诺夫哥罗德机场"},
        "GOT":{name:"哥德堡",gj:"gj",airport:"哥德堡机场"},
        "GSE":{name:"哥德堡",gj:"gj",airport:"Gothenburg Saeve Apt"},
        "GRZ":{name:"格拉滋",gj:"gj",airport:"格拉茨"},
        "HAJ":{name:"汉诺威",gj:"gj",airport:"汉诺威 朗根哈根机场"},
        "ZVR":{name:"汉诺威",gj:"gj",airport:"Hanover Hauptbahnhof Rail Station"},
        "HAM":{name:"汉堡",gj:"gj",airport:"汉堡机场"},
        "LBC":{name:"汉堡",gj:"gj",airport:"Hamburg Luebeck Airport"},
        "ZMB":{name:"汉堡",gj:"gj",airport:"Hamburg HBF Rail Station"},
        "IKT":{name:"伊尔库茨克",gj:"gj",airport:"伊尔库茨克机场"},
        "INN":{name:"茵斯布鲁克",gj:"gj",airport:"茵斯布鲁克机场"},
        "INV":{name:"因弗内斯",gj:"gj",airport:"因弗内斯"},
        "JER":{name:"泽西",gj:"gj",airport:"泽西机场"},
        "KHV":{name:"哈巴罗夫斯克",gj:"gj",airport:"伯力机场"},
        "LBA":{name:"利兹",gj:"gj",airport:"利兹机场"},
        "LBI":{name:"阿尔比",gj:"gj",airport:"阿尔比"},
        "LCA":{name:"拉纳卡",gj:"gj",airport:"拉纳卡机场"},
        "LEJ":{name:"莱比锡",gj:"gj",airport:"莱比锡哈勒机场"},
        "LJU":{name:"卢布尔雅那",gj:"gj",airport:"卢布尔雅那"},
        "LPL":{name:"利物浦",gj:"gj",airport:"利物浦约翰列侬机场"},
        "LUX":{name:"卢森堡",gj:"gj",airport:"卢森堡机场"},
        "LYN":{name:"里昂",gj:"gj",airport:"Lyon Bron Apt"},
        "LYS":{name:"里昂",gj:"gj",airport:"里昂机场"},
        "XYD":{name:"里昂",gj:"gj",airport:"Lyon Part-Dieu Rail Station"},
        "XYL":{name:"里昂",gj:"gj",airport:"Lyon Perrache Rail Station"},
        "LYX":{name:"利德",gj:"gj",airport:"利德"},
        "MAN":{name:"曼彻斯特",gj:"gj",airport:"曼彻斯特机场"},
        "QQM":{name:"曼彻斯特",gj:"gj",airport:"Manchester Piccadilly Rail Station"},
        "MLA":{name:"马耳他",gj:"gj",airport:"马耳他机场"},
        "MPL":{name:"蒙彼利埃",gj:"gj",airport:"蒙彼利埃地中海机场"},
        "MRS":{name:"马赛",gj:"gj",airport:"马赛普罗旺斯机场"},
        "MVA":{name:"雷克雅未克",gj:"gj",airport:"米湖"},
        "NAP":{name:"那不勒斯",gj:"gj",airport:"那不勒斯机场"},
        "ZMI":{name:"那布勒斯",gj:"gj",airport:"MEPGE"},
        "NCE":{name:"尼斯",gj:"gj",airport:"尼斯蓝色海岸机场"},
        "NCL":{name:"纽卡斯尔",gj:"gj",airport:"纽卡斯尔机场"},
        "NIC":{name:"尼科西亚",gj:"gj",airport:"NICOSIA"},
        "NIM":{name:"尼亚美",gj:"gj",airport:"尼亚美机场"},
        "NTE":{name:"南特",gj:"gj",airport:"南特"},
        "QJZ":{name:"南特",gj:"gj",airport:"Nantes Rail Station"},
        "NUE":{name:"纽伦堡",gj:"gj",airport:"纽伦堡机场"},
        "ZAQ":{name:"纽伦堡",gj:"gj",airport:"Nuremberg Main Railway Station"},
        "OPO":{name:"波尔图",gj:"gj",airport:"波尔图机场"},
        "ORE":{name:"奥尔良",gj:"gj",airport:"奥尔良"},
        "ORK":{name:"科克",gj:"gj",airport:"科克"},
        "OSL":{name:"奥斯陆",gj:"gj",airport:"奥斯陆机场"},
        "TRF":{name:"奥斯陆",gj:"gj",airport:"桑纳菲奥尔"},
        "XZO":{name:"奥斯陆",gj:"gj",airport:"Oslo Central Rail Station"},
        "PDL":{name:"蓬塔德尔加达",gj:"gj",airport:"蓬塔德尔加达"},
        "PLH":{name:"普利茅斯",gj:"gj",airport:"普利茅斯"},
        "PMI":{name:"马略卡岛帕尔马",gj:"gj",airport:"马略卡岛帕尔马机场"},
        "PRG":{name:"布拉格",gj:"gj",airport:"布拉格机场"},
        "QUA":{name:"泉州",gj:"gj",airport:"Puttgarden Off-Line Point"},
        "QVU":{name:"瓦杜兹",gj:"gj",airport:"Vaduz Off-Line Point"},
        "RIX":{name:"里加",gj:"gj",airport:"里加机场"},
        "QRH":{name:"鹿特丹",gj:"gj",airport:"Rotterdam Central Rail Station"},
        "RTM":{name:"鹿特丹",gj:"gj",airport:"鹿特丹机场"},
        "SAI":{name:"圣马办诺",gj:"gj",airport:"San Marino"},
        "SNN":{name:"香浓",gj:"gj",airport:"香农"},
        "SOF":{name:"索非亚",gj:"gj",airport:"索非亚机场"},
        "STR":{name:"斯图加特",gj:"gj",airport:"斯图加特机场"},
        "ZWS":{name:"斯图加特",gj:"gj",airport:"Stuttgart Rail Station"},
        "SVQ":{name:"塞维利亚",gj:"gj",airport:"塞维莱"},
        "TBS":{name:"第比利斯",gj:"gj",airport:"第比利斯机场"},
        "TLL":{name:"塔林",gj:"gj",airport:"伦纳特·梅里塔林机场"},
        "TMP":{name:"坦佩雷",gj:"gj",airport:"坦佩雷"},
        "TRN":{name:"都灵",gj:"gj",airport:"都灵机场"},
        "ZTC":{name:"都灵",gj:"gj",airport:"TURIN"},
        "UIP":{name:"坎佩尔",gj:"gj",airport:"坎佩尔"},
        "UUS":{name:"南萨哈林斯克",gj:"gj",airport:"南萨哈林斯克机场"},
        "TSF":{name:"威尼斯",gj:"gj",airport:"特雷维索"},
        "VCE":{name:"威尼斯",gj:"gj",airport:"威尼斯机场"},
        "VIT":{name:"维多利亚",gj:"gj",airport:"维多利亚"},
        "VNO":{name:"维尔纽斯",gj:"gj",airport:"维尔纽斯机场"},
        "QBS":{name:"维罗纳",gj:"gj",airport:"Verona Brescia Off-Line Point"},
        "VBS":{name:"布雷西亚",gj:"gj",airport:"Brescia Montichiari机场"},
        "VRN":{name:"维罗纳",gj:"gj",airport:"维罗纳机场"},
        "VTE":{name:"万象",gj:"gj",airport:"万象瓦岱机场"},
        "WAT":{name:"沃特福德",gj:"gj",airport:"沃特福德"},
        "WAW":{name:"华沙",gj:"gj",airport:"华沙萧邦机场"},
        "XMM":{name:"摩纳哥",gj:"gj",airport:"Monaco Monte Carlo Off-Line Pt"},
        "XTN":{name:"湘潭",gj:"gj",airport:"Tourcoing Off-Line Pt"},
        "ZAG":{name:"萨格勒布",gj:"gj",airport:"萨格勒布"},
        "ACA":{name:"阿卡普尔科",gj:"gj",airport:"阿卡普尔科机场"},
        "AGS":{name:"乔治亚州",gj:"gj",airport:"Augusta Regional机场"},
        "DNL":{name:"奥古斯塔",gj:"gj",airport:"Augusta Daniel Field"},
        "AGU":{name:"阿瓜斯卡连特斯",gj:"gj",airport:"阿瓜斯卡连特斯机场"},
        "ANC":{name:"安克雷奇",gj:"gj",airport:"泰德·史蒂文斯安克雷奇机场"},
        "EDF":{name:"安科雷奇",gj:"gj",airport:"Anchorage Elmendorf AFB"},
        "MRI":{name:"安科雷奇",gj:"gj",airport:"Anchorage Merrill Field"},
        "AOB":{name:"安娜堡",gj:"gj",airport:"安娜堡"},
        "ASH":{name:"纳什维尔",gj:"gj",airport:"Nashua"},
        "AUS":{name:"奥斯汀",gj:"gj",airport:"奥斯汀贝格斯特罗姆机场"},
        "MMR":{name:"奥斯汀",gj:"gj",airport:"Austin Camp Maybry AHP Airport"},
        "BBB":{name:"圣比埃尔和密克隆",gj:"gj",airport:"Benson"},
        "BCV":{name:"贝尔莫潘",gj:"gj",airport:"Belmopan"},
        "BHM":{name:"伯明翰",gj:"gj",airport:"伯明翰舒特尔斯沃思机场"},
        "BJX":{name:"莱昂瓜纳华托",gj:"gj",airport:"莱昂？瓜纳华托"},
        "BNA":{name:"纳什维尔",gj:"gj",airport:"纳什维尔机场"},
        "BOI":{name:"博伊西",gj:"gj",airport:"博伊西机场"},
        "BMT":{name:"博蒙特",gj:"gj",airport:"Beaumont Municipal Apt"},
        "BPT":{name:"博蒙特",gj:"gj",airport:"博蒙特"},
        "BTR":{name:"巴吞鲁日",gj:"gj",airport:"巴吞鲁日(瑞安)机场"},
        "EBR":{name:"巴吞鲁日",gj:"gj",airport:"Baton Rouge Downtown Apt"},
        "BTV":{name:"柏林顿",gj:"gj",airport:"柏林顿机场"},
        "BUF":{name:"布法罗",gj:"gj",airport:"布法罗机场"},
        "BWI":{name:"巴尔的摩",gj:"gj",airport:"古德·马歇尔机场"},
        "GBO":{name:"巴尔地摩",gj:"gj",airport:"Baltimore Greenbelt Airport"},
        "MTN":{name:"马里兰",gj:"gj",airport:"马丁州立机场"},
        "ZBP":{name:"巴尔地摩",gj:"gj",airport:"Baltimore Rail Station"},
        "CAE":{name:"哥伦比亚",gj:"gj",airport:"哥伦比亚梅特勒波利滕机场"},
        "CUB":{name:"哥伦比亚",gj:"gj",airport:"Columbia Owens Field"},
        "MMT":{name:"哥伦比亚",gj:"gj",airport:"Columbia McEntire ANGB"},
        "CHS":{name:"查尔斯顿",gj:"gj",airport:"查尔斯顿AFB机场"},
        "CLL":{name:"布拉索斯",gj:"gj",airport:"Easterwood Field机场"},
        "CLT":{name:"夏洛特",gj:"gj",airport:"夏洛特/道格拉斯机场"},
        "AFF":{name:"科罗拉多斯普林",gj:"gj",airport:"Colorado Springs USAF Academy Airport"},
        "COS":{name:"科罗拉多斯普林",gj:"gj",airport:"科罗拉多斯普林"},
        "FCS":{name:"科罗拉多斯普林",gj:"gj",airport:"Colorado Butts AAF"},
        "CRP":{name:"科珀斯克里斯蒂",gj:"gj",airport:"科珀斯克里斯蒂机场"},
        "CUX":{name:"科珀斯科里斯蒂",gj:"gj",airport:"Corpus Christi Cuddihy Field"},
        "NGP":{name:"科珀斯科里斯蒂",gj:"gj",airport:"Corpus Christi NAS"},
        "NGW":{name:"科珀斯科里斯蒂",gj:"gj",airport:"Corpus Christi Cabaniss Field"},
        "CUN":{name:"坎昆",gj:"gj",airport:"坎昆机场"},
        "CUU":{name:"奇瓦瓦",gj:"gj",airport:"奇瓦瓦机场"},
        "CZM":{name:"科苏梅尔",gj:"gj",airport:"科苏梅尔机场"},
        "DAB":{name:"代托纳比奇",gj:"gj",airport:"代托纳比奇"},
        "DAY":{name:"戴顿",gj:"gj",airport:"戴顿"},
        "DWF":{name:"戴顿",gj:"gj",airport:"Dayton Wright AFB"},
        "FFO":{name:"戴顿",gj:"gj",airport:"Dayton Patterson AFB"},
        "MGY":{name:"戴顿",gj:"gj",airport:"Dayton Montgomery County Apt"},
        "FLL":{name:"劳德代尔堡",gj:"gj",airport:"劳德代尔堡－好莱坞机场"},
        "FXE":{name:"劳德尔堡",gj:"gj",airport:"Fort Lauderdale Executive Apt"},
        "ZFT":{name:"劳德尔堡",gj:"gj",airport:"Fort Lauderdale Rail Station"},
        "FMY":{name:"迈尔斯堡",gj:"gj",airport:"迈尔斯堡"},
        "RSW":{name:"迈尔斯堡",gj:"gj",airport:"FORT MYERS SW FLO"},
        "FUN":{name:"富纳富提",gj:"gj",airport:"富纳富蒂"},
        "GDL":{name:"瓜达拉哈拉",gj:"gj",airport:"瓜达拉哈拉"},
        "GEG":{name:"斯波坎",gj:"gj",airport:"斯波坎机场"},
        "SFF":{name:"斯波坎",gj:"gj",airport:"Spokane Felts Field"},
        "SKA":{name:"斯波坎",gj:"gj",airport:"Spokane Fairchild AFB"},
        "GGE":{name:"乔治敦",gj:"gj",airport:"Georgetown"},
        "GGG":{name:"梵蒂冈城",gj:"gj",airport:"朗维尤"},
        "GPT":{name:"格尔夫波特",gj:"gj",airport:"格尔夫波特"},
        "GSO":{name:"格林斯伯勒",gj:"gj",airport:"格林斯伯勒"},
        "GDC":{name:"格林维尔",gj:"gj",airport:"Greenville Donaldson Center Apt"},
        "GMU":{name:"格林维尔",gj:"gj",airport:"Greenville Downtown Apt"},
        "GSP":{name:"格林维尔",gj:"gj",airport:"格林维尔"},
        "GUA":{name:"危地马拉城",gj:"gj",airport:"危地马拉城机场"},
        "HAR":{name:"哈里斯堡",gj:"gj",airport:"哈里斯堡"},
        "MDT":{name:"哈里斯堡",gj:"gj",airport:"哈里斯堡机场"},
        "ZUG":{name:"哈里斯堡",gj:"gj",airport:"Harrisburg Rail Station"},
        "HIR":{name:"霍尼亚拉",gj:"gj",airport:"霍尼亚拉"},
        "AAP":{name:"休斯顿",gj:"gj",airport:"Houston Andrau Airpark"},
        "DWH":{name:"休斯顿",gj:"gj",airport:"Houston David Wayne Hooks Apt"},
        "EFD":{name:"休斯顿",gj:"gj",airport:"Houston Ellington Field"},
        "HOU":{name:"休斯顿",gj:"gj",airport:"休斯顿机场"},
        "IAH":{name:"休斯敦",gj:"gj",airport:"休斯敦机场"},
        "IWS":{name:"休斯顿",gj:"gj",airport:"Houston West Houston Apt"},
        "JDX":{name:"休斯顿",gj:"gj",airport:"Houston Central Business District H/P"},
        "JGP":{name:"休斯顿",gj:"gj",airport:"Houston Greenway Plaza H/P"},
        "JGQ":{name:"休斯顿",gj:"gj",airport:"Houston Transco Tower Galleria H/P"},
        "JMA":{name:"休斯顿",gj:"gj",airport:"Houston Marriott Astrodome"},
        "JPT":{name:"休斯顿",gj:"gj",airport:"Houston Park Ten H/P"},
        "JWH":{name:"休斯顿",gj:"gj",airport:"Houston Westchase Hilton Helipad"},
        "JWL":{name:"休斯顿",gj:"gj",airport:"Houston Woodlands H/P"},
        "SGR":{name:"休斯顿",gj:"gj",airport:"SUGAR LAND TX"},
        "SPX":{name:"休斯顿",gj:"gj",airport:"Houston Spaceland Apt"},
        "HRL":{name:"哈灵根",gj:"gj",airport:"哈灵根"},
        "HSV":{name:"亨茨维尔",gj:"gj",airport:"亨茨维尔机场"},
        "HUA":{name:"亨次维尔",gj:"gj",airport:"Huntsville Redstone AAF"},
        "BEC":{name:"威奇塔福尔斯",gj:"gj",airport:"Wichita Beech Apt"},
        "CEA":{name:"威奇塔福尔斯",gj:"gj",airport:"Wichita Cessna Aircraft Field"},
        "IAB":{name:"威奇塔福尔斯",gj:"gj",airport:"Wichita McConnel AFB"},
        "ICT":{name:"威奇塔福尔斯",gj:"gj",airport:"威奇塔 福尔斯"},
        "IND":{name:"印第安纳波利斯",gj:"gj",airport:"印第安纳波利斯机场"},
        "INU":{name:"瑙鲁",gj:"gj",airport:"瑙鲁岛"},
        "HKS":{name:"杰克逊",gj:"gj",airport:"Jackson Hawkins Field"},
        "JAN":{name:"杰克逊",gj:"gj",airport:"杰克逊"},
        "CRG":{name:"杰克逊维尔",gj:"gj",airport:"Jacksonville Craig Municipal Apt"},
        "JAX":{name:"杰克逊维尔",gj:"gj",airport:"杰克逊维尔机场"},
        "NIP":{name:"杰克逊维尔",gj:"gj",airport:"Jacksonville NAS"},
        "NZC":{name:"杰克逊维尔",gj:"gj",airport:"Jacksonville Cecil NAS"},
        "HSH":{name:"拉斯维加斯",gj:"gj",airport:"Las Vegas Henderson Sky Harbor Apt"},
        "LAS":{name:"拉斯维加斯",gj:"gj",airport:"拉斯维加斯麦卡伦国际机场机场"},
        "LSV":{name:"拉斯维加斯",gj:"gj",airport:"Las Vegas Nellis AFB"},
        "VGT":{name:"拉斯维加斯",gj:"gj",airport:"LAS VEGAS NORTH"},
        "LBB":{name:"拉伯克",gj:"gj",airport:"拉伯克"},
        "REE":{name:"拉伯克",gj:"gj",airport:"Lubbock Reese AFB"},
        "LCH":{name:"莱克查尔斯",gj:"gj",airport:"莱克查尔斯"},
        "ARA":{name:"拉斐特",gj:"gj",airport:"Lafayette New Iberia Apt"},
        "LFT":{name:"拉斐特",gj:"gj",airport:"拉斐特"},
        "LIT":{name:"小石城",gj:"gj",airport:"小石城"},
        "MAF":{name:"米德兰",gj:"gj",airport:"米德兰"},
        "MDD":{name:"米德兰",gj:"gj",airport:"Midland Airpark"},
        "MAM":{name:"迈纳麦",gj:"gj",airport:"马塔莫罗斯"},
        "MEM":{name:"孟菲斯",gj:"gj",airport:"孟菲斯机场"},
        "NQA":{name:"孟菲斯",gj:"gj",airport:"Memphis NAS"},
        "AZP":{name:"墨西哥城",gj:"gj",airport:"Mexico City Atizapan Apt"},
        "MEX":{name:"墨西哥",gj:"gj",airport:"墨西哥城机场"},
        "NLU":{name:"墨西哥城",gj:"gj",airport:"Mexico City Santa Lucia Apt"},
        "MFE":{name:"麦卡伦",gj:"gj",airport:"麦卡伦"},
        "MFR":{name:"梅德福",gj:"gj",airport:"梅德福"},
        "MGA":{name:"马那瓜",gj:"gj",airport:"马那瓜"},
        "GUN":{name:"蒙哥马利",gj:"gj",airport:"Montgomery Gunter AFB"},
        "MGM":{name:"蒙哥马利",gj:"gj",airport:"蒙哥马利机场"},
        "MXF":{name:"蒙哥马利",gj:"gj",airport:"Montgomery Maxwell AFB"},
        "MHT":{name:"曼彻斯特",gj:"gj",airport:"曼彻斯特"},
        "JDM":{name:"迈阿密",gj:"gj",airport:"MIAMI DOWNTOWN H"},
        "MIA":{name:"迈阿密",gj:"gj",airport:"迈阿密机场"},
        "MPB":{name:"迈阿密",gj:"gj",airport:"MIAMI SPB"},
        "OPF":{name:"迈阿密",gj:"gj",airport:"Miami Opa Locka Apt"},
        "TMB":{name:"迈阿密",gj:"gj",airport:"Miami New Tamiami Apt"},
        "TNT":{name:"迈阿密",gj:"gj",airport:"Miami Dade Collier Apt"},
        "MID":{name:"梅里达",gj:"gj",airport:"梅里达"},
        "MKE":{name:"密尔沃基",gj:"gj",airport:"密尔沃基"},
        "MWC":{name:"密尔沃基",gj:"gj",airport:"Milwaukee Lawrence J Timmerman Apt"},
        "ZML":{name:"密尔沃基",gj:"gj",airport:"Milwaukee Rail Station"},
        "MLB":{name:"墨尔本",gj:"gj",airport:"墨尔本"},
        "MLU":{name:"门罗",gj:"gj",airport:"门罗"},
        "BFM":{name:"莫比尔",gj:"gj",airport:"Mobile Downtown机场"},
        "MOB":{name:"莫比尔",gj:"gj",airport:"莫比尔机场"},
        "FCM":{name:"明尼阿波利斯",gj:"gj",airport:"US"},
        "JDT":{name:"明尼阿波利斯",gj:"gj",airport:"MINIM"},
        "MIC":{name:"明尼阿波利斯",gj:"gj",airport:"MINI"},
        "MSP":{name:"明尼阿波利斯",gj:"gj",airport:"明尼阿波利斯—圣保罗机场"},
        "STP":{name:"明尼阿波利斯",gj:"gj",airport:"Minneapolis Downtown Airport"},
        "MSY":{name:"新奥尔良",gj:"gj",airport:"新奥尔良机场"},
        "NBG":{name:"新奥尔良",gj:"gj",airport:"New Orleans Alvin Calendar NAS"},
        "NEW":{name:"新奥尔良",gj:"gj",airport:"New Orleans Lakefront Apt"},
        "MTY":{name:"蒙特雷",gj:"gj",airport:"墨西哥蒙特雷机场"},
        "NTR":{name:"蒙特雷",gj:"gj",airport:"Monterrey del Norte Apt"},
        "MZT":{name:"马萨特兰",gj:"gj",airport:"马萨特兰"},
        "JCE":{name:"奥克兰",gj:"gj",airport:"Oakland Convention Center H/P"},
        "OAK":{name:"奥克兰",gj:"gj",airport:"加州奥克兰机场"},
        "DWN":{name:"俄克拉何马城",gj:"gj",airport:"Oklahoma City Downtown Airpark"},
        "OKC":{name:"俄克拉荷马城",gj:"gj",airport:"俄克拉荷马城机场"},
        "PWA":{name:"俄克拉何马城",gj:"gj",airport:"Oklahoma City Wiley Post Apt"},
        "TIK":{name:"俄克拉何马城",gj:"gj",airport:"Oklahoma City Tinker AFB"},
        "MIQ":{name:"奥马哈",gj:"gj",airport:"Omaha Millard Apt"},
        "OFF":{name:"奥马哈",gj:"gj",airport:"Omaha Offutt Off-Line Point"},
        "OMA":{name:"奥马哈",gj:"gj",airport:"奥马哈"},
        "LNA":{name:"西棕榈滩",gj:"gj",airport:"West Palm Beach County Apt"},
        "PBI":{name:"西棕榈滩",gj:"gj",airport:"西棕榈滩"},
        "ZWP":{name:"西棕榈滩",gj:"gj",airport:"West Palm Beach Rail Station"},
        "PDX":{name:"波特兰",gj:"gj",airport:"波特兰机场"},
        "MUV":{name:"费城",gj:"gj",airport:"Philadelphia Mustin Aux Landing Field"},
        "PHL":{name:"费城",gj:"gj",airport:"费城机场"},
        "PNE":{name:"费城",gj:"gj",airport:"Philadelphia North Philadelphia Apt"},
        "PSQ":{name:"费城",gj:"gj",airport:"Philadelphia SPB"},
        "TTN":{name:"费城",gj:"gj",airport:"特伦顿"},
        "ZFV":{name:"费城",gj:"gj",airport:"Philadelphia Rail Station"},
        "ZHC":{name:"费城",gj:"gj",airport:"Philadelphia North Rail Station"},
        "ZTN":{name:"费城",gj:"gj",airport:"Philadelphia Trenton Rail Station"},
        "DVT":{name:"菲尼克斯",gj:"gj",airport:"凤凰城鹿谷/菲尼克斯迪尔山谷机场"},
        "LUF":{name:"菲尼克斯",gj:"gj",airport:"Phoenix Luke AFB"},
        "PHX":{name:"菲尼克斯",gj:"gj",airport:"菲尼克斯天港机场"},
        "SCF":{name:"菲尼克斯",gj:"gj",airport:"SOFIA"},
        "AGC":{name:"匹兹堡",gj:"gj",airport:"Allegheny County机场"},
        "CVA":{name:"匹斯堡",gj:"gj",airport:"Pittsburgh Civic Arena H/P"},
        "PIT":{name:"匹兹堡",gj:"gj",airport:"匹兹堡机场"},
        "NDP":{name:"彭萨科拉",gj:"gj",airport:"Pensacola Ellyson NAS"},
        "NPA":{name:"彭萨科拉",gj:"gj",airport:"Pensacola NAS"},
        "NUN":{name:"彭萨科拉",gj:"gj",airport:"Pensacola Sautley NAS"},
        "PNS":{name:"彭萨科拉",gj:"gj",airport:"彭萨科拉机场"},
        "POM":{name:"莫尔兹比港",gj:"gj",airport:"莫尔兹比港机场"},
        "PPG":{name:"帕果帕里",gj:"gj",airport:"帕果帕果"},
        "PPT":{name:"帕皮提",gj:"gj",airport:"帕皮提机场"},
        "PSP":{name:"棕榈泉",gj:"gj",airport:"棕榈泉"},
        "UDD":{name:"棕榈泉",gj:"gj",airport:"PALM SPRG BERM CA"},
        "PVD":{name:"普罗维登斯",gj:"gj",airport:"普罗维登斯机场"},
        "PVR":{name:"巴亚尔塔港",gj:"gj",airport:"巴亚尔塔港"},
        "PWM":{name:"波特兰",gj:"gj",airport:"波特兰"},
        "RDU":{name:"罗利达勒姆",gj:"gj",airport:"罗利达勒姆机场"},
        "RIC":{name:"里士满",gj:"gj",airport:"里士满机场"},
        "RNO":{name:"里诺",gj:"gj",airport:"里诺"},
        "ROC":{name:"罗切斯特",gj:"gj",airport:"罗切斯特"},
        "SAL":{name:"圣萨尔瓦多",gj:"gj",airport:"圣萨尔瓦多 科马拉帕机场"},
        "MYF":{name:"圣迭弋",gj:"gj",airport:"SAN DIEGO MONTGOM"},
        "NKX":{name:"圣迭弋",gj:"gj",airport:"San Diego Miramar NAS"},
        "NZY":{name:"圣迭弋",gj:"gj",airport:"San Diego North Island NAS"},
        "SAN":{name:"圣迭戈",gj:"gj",airport:"圣迭戈机场"},
        "SDM":{name:"圣迭弋",gj:"gj",airport:"SAN DIEGO BROWN"},
        "SEE":{name:"圣迭弋",gj:"gj",airport:"San Diego Gillespie Field"},
        "SAP":{name:"圣佩德罗苏拉",gj:"gj",airport:"圣佩德罗苏拉"},
        "MDA":{name:"圣安敦",gj:"gj",airport:"San Antonio Martindale AAF"},
        "RND":{name:"圣安敦",gj:"gj",airport:"San Antonio Randolph AFB"},
        "SAT":{name:"圣安东尼奥",gj:"gj",airport:"圣安东尼奥机场"},
        "SKF":{name:"圣安敦",gj:"gj",airport:"San Antonio Kelly AFB"},
        "SSF":{name:"圣安敦",gj:"gj",airport:"San Antonio Stinson Apt"},
        "SAV":{name:"萨凡纳",gj:"gj",airport:"萨凡纳机场"},
        "SVN":{name:"萨瓦纳",gj:"gj",airport:"Savannah Hunter AAF"},
        "SBA":{name:"圣芭芭拉",gj:"gj",airport:"圣芭芭拉机场"},
        "SZN":{name:"圣巴巴拉",gj:"gj",airport:"Santa Barbara Santa Cruz Island Apt"},
        "LJC":{name:"路易斯维尔",gj:"gj",airport:"Louisville Intercontinental Apt"},
        "LOU":{name:"路易斯维尔",gj:"gj",airport:"Louisville Bowman Field Airport"},
        "SDF":{name:"路易斯维尔",gj:"gj",airport:"路易斯维尔机场"},
        "BAD":{name:"什里夫波特",gj:"gj",airport:"Shreveport Barksdale AFB"},
        "DTN":{name:"什里夫波特",gj:"gj",airport:"Shreveport Downtown Apt"},
        "SHV":{name:"什里夫波特",gj:"gj",airport:"什里夫波特"},
        "SHX":{name:"沙格鲁克",gj:"gj",airport:"沙格勒克"},
        "RHV":{name:"圣何塞",gj:"gj",airport:"San Jose Reid-Hillview Apt"},
        "SJC":{name:"圣何塞",gj:"gj",airport:"诺曼?米内塔圣何塞机场"},
        "ZJO":{name:"圣何塞",gj:"gj",airport:"San Jose Bus Station"},
        "SJD":{name:"圣约瑟卡博",gj:"gj",airport:"圣约瑟卡博"},
        "SJO":{name:"圣何塞",gj:"gj",airport:"胡安 圣玛利亚机场"},
        "SYQ":{name:"圣何塞",gj:"gj",airport:"San Jose Tobias Bolanos Apt"},
        "SLC":{name:"盐湖城",gj:"gj",airport:"盐湖城机场"},
        "SLP":{name:"圣路易斯波托西",gj:"gj",airport:"圣路易斯波托西"},
        "SLW":{name:"萨尔蒂罗",gj:"gj",airport:"萨尔蒂罗"},
        "SRQ":{name:"布雷登顿",gj:"gj",airport:"布雷登顿"},
        "CPS":{name:"圣露易斯",gj:"gj",airport:"St Louis Bi-State Parks Airport"},
        "STL":{name:"圣路易斯",gj:"gj",airport:"圣路易斯机场"},
        "SUS":{name:"圣露易斯",gj:"gj",airport:"St Louis Spirit of St Louis Apt"},
        "SVA":{name:"塞维利亚",gj:"gj",airport:"萨文格"},
        "SYR":{name:"雪城",gj:"gj",airport:"雪城汉考克机场"},
        "TAM":{name:"坦皮科",gj:"gj",airport:"坦皮科"},
        "TBU":{name:"汤加塔布罗",gj:"gj",airport:"汤加塔布罗"},
        "TGU":{name:"特古西加尔巴",gj:"gj",airport:"特古西加尔巴"},
        "TLH":{name:"塔拉哈西",gj:"gj",airport:"塔拉哈西机场"},
        "KYO":{name:"坦帕",gj:"gj",airport:"Tampa Topp of Tampa Apt"},
        "MCF":{name:"坦帕",gj:"gj",airport:"Tampa Macdill AFB"},
        "TPA":{name:"坦帕",gj:"gj",airport:"坦帕机场"},
        "TPF":{name:"坦帕",gj:"gj",airport:"Tampa Peter O'Knight Apt"},
        "TRC":{name:"托雷翁",gj:"gj",airport:"托雷翁"},
        "TRW":{name:"塔拉瓦",gj:"gj",airport:"塔拉瓦"},
        "RVS":{name:"塔尔萨",gj:"gj",airport:"TULSA"},
        "TUL":{name:"塔尔萨",gj:"gj",airport:"塔尔萨机场"},
        "TYS":{name:"诺克斯维尔",gj:"gj",airport:"诺克斯维尔"},
        "VER":{name:"韦拉克鲁斯",gj:"gj",airport:"韦拉克鲁斯"},
        "VLI":{name:"维拉港",gj:"gj",airport:"维拉港"},
        "VPZ":{name:"瓦乐帕莱索",gj:"gj",airport:"瓦尔帕莱索"},
        "YAA":{name:"阿纳希姆莱克",gj:"gj",airport:"阿纳希姆莱克"},
        "YAC":{name:"卡特莱克",gj:"gj",airport:"卡特莱克"},
        "YAF":{name:"阿斯贝斯敦港",gj:"gj",airport:"阿斯贝斯敦港"},
        "YAG":{name:"弗朗西斯堡",gj:"gj",airport:"弗朗西斯堡机场"},
        "YAL":{name:"阿莱特湾",gj:"gj",airport:"阿莱特湾"},
        "YAM":{name:"苏圣玛丽",gj:"gj",airport:"苏圣玛丽机场"},
        "YAT":{name:"阿塔瓦皮斯",gj:"gj",airport:"阿塔瓦皮斯"},
        "YAY":{name:"圣安东尼",gj:"gj",airport:"圣安东尼"},
        "YAZ":{name:"图芬奴",gj:"gj",airport:"图芬奴机场"},
        "YTP":{name:"托菲诺",gj:"gj",airport:"Tofino SPB"},
        "YBC":{name:"贝科莫",gj:"gj",airport:"贝科莫机场"},
        "YBE":{name:"铀城",gj:"gj",airport:"铀城机场"},
        "YBF":{name:"邦尼维尔",gj:"gj",airport:"邦尼维尔机场"},
        "YBG":{name:"巴戈特维尔",gj:"gj",airport:"巴戈特维尔机场"},
        "YBI":{name:"布莱克蒂克",gj:"gj",airport:"布莱克蒂克"},
        "YBJ":{name:"拜约翰比茨",gj:"gj",airport:"拜约翰比茨"},
        "YBK":{name:"贝克湖",gj:"gj",airport:"贝克湖机场"},
        "YBL":{name:"坎贝尔",gj:"gj",airport:"坎贝尔河机场"},
        "YHH":{name:"坎贝尔河",gj:"gj",airport:"Campbell River Harbor SPB"},
        "YBM":{name:"布朗森",gj:"gj",airport:"布朗森"},
        "YBR":{name:"布兰登",gj:"gj",airport:"布兰登机场"},
        "YBT":{name:"布朗欠特",gj:"gj",airport:"布朗欠特"},
        "YBV":{name:"贝伦斯里弗",gj:"gj",airport:"贝伦斯河机场"},
        "YBX":{name:"布朗萨布隆",gj:"gj",airport:"布朗萨布隆机场"},
        "YBY":{name:"邦尼维尔",gj:"gj",airport:"邦尼维尔"},
        "YCB":{name:"剑桥湾",gj:"gj",airport:"剑桥湾机场"},
        "YCC":{name:"康沃尔",gj:"gj",airport:"康沃尔"},
        "YCD":{name:"纳奈莫",gj:"gj",airport:"纳奈莫机场"},
        "ZNA":{name:"纳奈莫",gj:"gj",airport:"NANAIMO HARBOUR"},
        "YCF":{name:"科特斯湾",gj:"gj",airport:"科特斯湾"},
        "YCG":{name:"卡斯加尔",gj:"gj",airport:"卡斯加尔"},
        "YCH":{name:"查塔姆",gj:"gj",airport:"查塔姆"},
        "YCL":{name:"夏洛",gj:"gj",airport:"夏洛"},
        "YCM":{name:"圣坎特黑利",gj:"gj",airport:"圣坎特黑利"},
        "YCN":{name:"科克伦",gj:"gj",airport:"科克伦"},
        "YCO":{name:"库格卢克图克",gj:"gj",airport:"库格卢克图克机场"},
        "YCQ":{name:"切特温德",gj:"gj",airport:"切特温德机场"},
        "YCR":{name:"克罗斯莱克",gj:"gj",airport:"克罗斯莱克"},
        "YCS":{name:"切斯特菲尔德因莱特",gj:"gj",airport:"切斯特菲尔德因莱特机场"},
        "YCY":{name:"克莱德",gj:"gj",airport:"克莱德河机场"},
        "YCZ":{name:"克雷斯敦",gj:"gj",airport:"克雷斯敦"},
        "YDA":{name:"道森",gj:"gj",airport:"道森城市机场"},
        "YDE":{name:"帕拉迪斯里弗",gj:"gj",airport:"帕拉迪斯里弗"},
        "YDF":{name:"迪尔莱克",gj:"gj",airport:"迪尔莱克"},
        "XDG":{name:"哈利法克斯",gj:"gj",airport:"Halifax Rail Station"},
        "YAW":{name:"哈利法克斯",gj:"gj",airport:"哈利法克斯机场"},
        "YHZ":{name:"哈利法克斯",gj:"gj",airport:"哈利法克斯罗伯特·洛恩·斯坦菲尔德机场"},
        "YWF":{name:"哈利法克斯",gj:"gj",airport:"Halifax Downtown Waterfront H/P"},
        "YKA":{name:"坎卢普斯",gj:"gj",airport:"坎卢普斯"},
        "XDW":{name:"鲁珀特王子城",gj:"gj",airport:"Prince Rupert Rail Station"},
        "YPR":{name:"凯恩岛",gj:"gj",airport:"鲁珀特王子港机场"},
        "ZSW":{name:"鲁珀特王子城",gj:"gj",airport:"PRINCE RUPERT BC"},
        "XFY":{name:"魁北克",gj:"gj",airport:"Quebec Ste Foy Rail Station"},
        "XFZ":{name:"魁北克",gj:"gj",airport:"Quebec Charny Rail Station"},
        "XLJ":{name:"魁北克",gj:"gj",airport:"Quebec Rail Station"},
        "XLK":{name:"魁北克",gj:"gj",airport:"Quebec Levis Rail Station"},
        "YQB":{name:"魁北克",gj:"gj",airport:"魁北克城机场"},
        "XEC":{name:"温莎",gj:"gj",airport:"Windsor Rail Station"},
        "YQG":{name:"温莎",gj:"gj",airport:"温莎机场"},
        "YQQ":{name:"科莫克斯",gj:"gj",airport:"科莫克斯"},
        "YQR":{name:"里贾纳",gj:"gj",airport:"里贾纳机场"},
        "YSJ":{name:"圣约翰",gj:"gj",airport:"圣约翰机场"},
        "YSP":{name:"瑟佛罗里达基斯",gj:"gj",airport:"瑟佛罗里达基斯马拉松机场"},
        "YUY":{name:"鲁安",gj:"gj",airport:"鲁安诺兰达机场"},
        "YXJ":{name:"福特圣约翰",gj:"gj",airport:"福特圣约翰机场"},
        "XDV":{name:"乔治王子城",gj:"gj",airport:"Prince George Rail Station"},
        "YXS":{name:"乔治皇子",gj:"gj",airport:"乔治皇子城机场"},
        "YXT":{name:"德瑞司",gj:"gj",airport:"德瑞司机场"},
        "YYF":{name:"彭蒂科顿",gj:"gj",airport:"彭蒂科顿机场"},
        "YYG":{name:"夏洛特城",gj:"gj",airport:"夏洛特城机场"},
        "YWH":{name:"维多利亚",gj:"gj",airport:"VICTORIA INNER"},
        "YYJ":{name:"维多利亚",gj:"gj",airport:"维多利亚机场"},
        "XAD":{name:"丘吉尔",gj:"gj",airport:"Churchill Rail Station"},
        "YYQ":{name:"丘吉尔",gj:"gj",airport:"丘吉尔机场"},
        "ZIH":{name:"锡瓦塔内霍",gj:"gj",airport:"锡瓦塔内霍"},
        "ZTM":{name:"沙马塔瓦",gj:"gj",airport:"沙马塔瓦"},
        "ASU":{name:"亚松森",gj:"gj",airport:"亚松森"},
        "BDC":{name:"巴腊多科尔达",gj:"gj",airport:"巴腊多科尔达"},
        "BGI":{name:"布里奇敦",gj:"gj",airport:"巴巴多斯"},
        "CAY":{name:"卡宴",gj:"gj",airport:"卡"},
        "CCC":{name:"科伯恩城",gj:"gj",airport:"Cayo Coco"},
        "CCS":{name:"加拉加斯",gj:"gj",airport:"加拉加斯机场"},
        "FDF":{name:"法兰西堡",gj:"gj",airport:"法兰西堡"},
        "GEO":{name:"乔治敦",gj:"gj",airport:"乔治敦"},
        "GYE":{name:"瓜亚基尔",gj:"gj",airport:"瓜亚基尔"},
        "HAV":{name:"哈瓦那",gj:"gj",airport:"哈瓦那何塞马蒂机场"},
        "KIN":{name:"金斯敦",gj:"gj",airport:"金斯敦诺曼·曼利机场"},
        "KTP":{name:"金斯敦",gj:"gj",airport:"KINGSTON TINSON"},
        "LIM":{name:"利马",gj:"gj",airport:"利马机场"},
        "LPB":{name:"拉巴斯",gj:"gj",airport:"EL ALTO机场"},
        "MVD":{name:"乌拉圭",gj:"gj",airport:"蒙得维的亚"},
        "NAS":{name:"拿骚",gj:"gj",airport:"拿骚"},
        "PID":{name:"拿骚",gj:"gj",airport:"NASSAU PARADISE I"},
        "WZY":{name:"拿骚",gj:"gj",airport:"NASSAU SPB"},
        "PAP":{name:"太子港国际",gj:"gj",airport:"太子港国际机场"},
        "POS":{name:"西班牙港",gj:"gj",airport:"西班牙港"},
        "PAC":{name:"巴拿马城",gj:"gj",airport:"PANAMA CITY PAITI"},
        "PTY":{name:"巴拿马城",gj:"gj",airport:"巴拿马城机场"},
        "GIG":{name:"里约热内卢",gj:"gj",airport:"里约热内卢 加利昂机场"},
        "SDU":{name:"里约热内卢",gj:"gj",airport:"圣杜蒙特机场"},
        "SCL":{name:"圣地亚哥",gj:"gj",airport:"圣地亚哥机场"},
        "ULC":{name:"圣地亚哥",gj:"gj",airport:"Santiago Los Cerrillos Apt"},
        "HEX":{name:"圣多明各",gj:"gj",airport:"Santo Domingo Herrera Apt"},
        "SDQ":{name:"圣多明各",gj:"gj",airport:"LAS AMERICAS机场"},
        "SIG":{name:"圣胡安",gj:"gj",airport:"SAN JUAN ISLA"},
        "SJU":{name:"路易斯·穆尼奥斯·马林",gj:"gj",airport:"路易斯·穆尼奥斯·马林机场"},
        "SRE":{name:"苏克雷",gj:"gj",airport:"苏克雷"},
        "SRZ":{name:"圣克鲁斯",gj:"gj",airport:"圣克鲁斯"},
        "VVI":{name:"圣克鲁斯",gj:"gj",airport:"SANTA CRUZ VIRU"},
        "RAD":{name:"罗德城",gj:"gj",airport:"Tortola Road Town Apt"},
        "TOV":{name:"罗德城",gj:"gj",airport:"托尔托拉"},
        "UIO":{name:"基多",gj:"gj",airport:"基多机场"},
        "ADE":{name:"亚丁",gj:"gj",airport:"亚丁"},
        "ASB":{name:"阿什哈巴德",gj:"gj",airport:"阿什哈巴德机场"},
        "BAK":{name:"巴库",gj:"gj",airport:"巴库"},
        "BEY":{name:"贝鲁特",gj:"gj",airport:"贝鲁特机场"},
        "BGW":{name:"巴格达",gj:"gj",airport:"巴格达机场"},
        "SDA":{name:"巴格达",gj:"gj",airport:"BAGHDAD SADDAM"},
        "BLR":{name:"班加罗尔",gj:"gj",airport:"班加罗尔机场"},
        "BOM":{name:"孟买",gj:"gj",airport:"孟买机场"},
        "CAI":{name:"开罗",gj:"gj",airport:"开罗机场"},
        "CCU":{name:"加尔各答",gj:"gj",airport:"加尔各答机场"},
        "CGP":{name:"吉大港",gj:"gj",airport:"吉大港"},
        "CMB":{name:"科伦坡",gj:"gj",airport:"班达拉奈克机场"},
        "RML":{name:"科伦坡",gj:"gj",airport:"Colombo Ratmalana Apt"},
        "CNX":{name:"清迈",gj:"gj",airport:"清迈机场"},
        "DAM":{name:"大马士革",gj:"gj",airport:"大马士革机场"},
        "DYU":{name:"杜尚别",gj:"gj",airport:"杜尚别机场"},
        "EVN":{name:"埃里温",gj:"gj",airport:"埃里温"},
        "FKS":{name:"福岛",gj:"gj",airport:"FUKUSHIMA"},
        "FNJ":{name:"平壤",gj:"gj",airport:"平壤机场"},
        "FRU":{name:"比什凯克",gj:"gj",airport:"马纳斯机场"},
        "GTK":{name:"甘托克",gj:"gj",airport:"Sungei Tekai"},
        "HIJ":{name:"广岛",gj:"gj",airport:"广岛机场"},
        "HIW":{name:"广岛",gj:"gj",airport:"Hiroshima West Apt"},
        "HYD":{name:"海德拉巴",gj:"gj",airport:"海德拉巴机场"},
        "JED":{name:"吉达",gj:"gj",airport:"阿卜杜勒-阿齐兹国王机场"},
        "KBL":{name:"喀布尔",gj:"gj",airport:"喀布尔机场"},
        "KDU":{name:"斯卡都",gj:"gj",airport:"斯卡都"},
        "KHI":{name:"卡拉奇",gj:"gj",airport:"卡拉奇机场"},
        "KIJ":{name:"新泻",gj:"gj",airport:"新泻机场"},
        "KMI":{name:"宫崎",gj:"gj",airport:"宫崎机场"},
        "KNC":{name:"吉安",gj:"gj",airport:"吉安机场"},
        "KOJ":{name:"鹿儿岛",gj:"gj",airport:"鹿儿岛机场"},
        "KRT":{name:"喀土穆",gj:"gj",airport:"喀土穆机场"},
        "KWI":{name:"科威特",gj:"gj",airport:"科威特机场"},
        "LHE":{name:"拉合尔",gj:"gj",airport:"拉合尔机场"},
        "LYP":{name:"费萨拉得巴",gj:"gj",airport:"费萨拉巴德"},
        "MAA":{name:"金奈",gj:"gj",airport:"金奈机场"},
        "MAJ":{name:"马珠罗",gj:"gj",airport:"马朱罗"},
        "MCT":{name:"马斯喀特",gj:"gj",airport:"马斯喀特机场"},
        "MLE":{name:"马累",gj:"gj",airport:"马累机场"},
        "MRU":{name:"毛里求斯",gj:"gj",airport:"毛里求斯机场"},
        "MHP":{name:"明斯克",gj:"gj",airport:"MINSK"},
        "MSQ":{name:"明斯克",gj:"gj",airport:"明斯克机场"},
        "MUX":{name:"木尔坦",gj:"gj",airport:"木尔坦"},
        "MXI":{name:"马蒂",gj:"gj",airport:"马蒂"},
        "NGS":{name:"长崎",gj:"gj",airport:"长崎机场"},
        "AHA":{name:"冲绳",gj:"gj",airport:"Okinawa Naha AFB"},
        "DNA":{name:"冲绳",gj:"gj",airport:"Okinawa Kadena AFB"},
        "OKA":{name:"冲绳",gj:"gj",airport:"那霸机场"},
        "ITM":{name:"大阪伊丹",gj:"gj",airport:"伊丹机场"},
        "KIX":{name:"大阪",gj:"gj",airport:"关西机场"},
        "ORG":{name:"帕拉马里博",gj:"gj",airport:"PARAMARIBO ZORG"},
        "PBM":{name:"帕拉马里博",gj:"gj",airport:"帕拉马里博"},
        "PEN":{name:"槟城",gj:"gj",airport:"槟城机场"},
        "PEW":{name:"白沙瓦",gj:"gj",airport:"白沙瓦机场"},
        "PNH":{name:"金边",gj:"gj",airport:"金边机场"},
        "PYX":{name:"芭堤雅",gj:"gj",airport:"帕塔亚"},
        "QJC":{name:"延布",gj:"gj",airport:"Thimphu Off-Line Point"},
        "RGN":{name:"仰光",gj:"gj",airport:"仰光机场"},
        "RUN":{name:"圣丹尼斯",gj:"gj",airport:"圣丹尼斯"},
        "SAH":{name:"亚丁",gj:"gj",airport:"亚丁机场"},
        "SDJ":{name:"仙台",gj:"gj",airport:"仙台机场"},
        "SEZ":{name:"维多利亚",gj:"gj",airport:"塞舌尔机场"},
        "SHJ":{name:"沙迦",gj:"gj",airport:"莎迦机场"},
        "TAS":{name:"塔什干",gj:"gj",airport:"塔什干机场"},
        "TOY":{name:"富山",gj:"gj",airport:"富山机场"},
        "TSE":{name:"阿斯塔纳",gj:"gj",airport:"阿斯塔纳机场"},
        "UET":{name:"奎达",gj:"gj",airport:"奎达"},
        "ULN":{name:"乌兰巴托",gj:"gj",airport:"乌兰巴托机场"},
        "HAH":{name:"莫罗尼",gj:"gj",airport:"MORONI HAHAYA"},
        "YVA":{name:"莫罗尼",gj:"gj",airport:"莫罗尼"},
        "TNN":{name:"台南",gj:"gj",airport:"台南机场"},
        "KHH":{name:"高雄",gj:"gj",airport:"高雄机场"},
        "TTG":{name:"台东",gj:"gj",airport:"台东志航机场"},
        "HUN":{name:"花莲",gj:"gj",airport:"花莲机场"},
        "CYI":{name:"嘉义",gj:"gj",airport:"嘉义机场"},
        "MES":{name:"棉兰",gj:"gj",airport:"棉兰机场"},
        "THR":{name:"德黑兰",gj:"gj",airport:"德黑兰机场"},
        "BTK":{name:"布拉茨克",gj:"gj",airport:"布拉茨克机场"},
        "CJJ":{name:"清州",gj:"gj",airport:"清州机场"},
        "YMQ":{name:"蒙特利尔",gj:"gj",airport:"蒙特利尔机场"},
        "TXL":{name:"柏林",gj:"gj",airport:"泰格尔机场"},
        "THF":{name:"柏林",gj:"gj",airport:"滕伯尔霍夫机场"},
        "SXF":{name:"柏林",gj:"gj",airport:"舍讷费尔德机场"},
        "VKO":{name:"莫斯科",gj:"gj",airport:"伏努科沃机场"},
        "HTA":{name:"赤塔",gj:"gj",airport:"赤塔机场"},
        "ASW":{name:"阿斯旺",gj:"gj",airport:"阿斯旺机场"},
        "WAS":{name:"华盛顿",gj:"gj",airport:"华盛顿机场"},
        "DTT":{name:"底特律",gj:"gj",airport:"底特律机场"},
        "LGB":{name:"长滩",gj:"gj",airport:"长滩机场"},
        "XSP":{name:"实里达",gj:"gj",airport:"实里达机场"},
        "LCX":{name:"龙岩",gj:"gj",airport:"福建龙岩冠豸山机场"},
        "BLH":{name:"加利福尼亚州",gj:"gj",airport:"加利福尼亚布莱斯机场"},
        "BDN":{name:"希拉本德",gj:"gj",airport:"希拉本德机场"},
        "DMK":{name:"曼谷",gj:"gj",airport:"廊曼机场"},
        "GYR":{name:"古德伊尔",gj:"gj",airport:"菲尼克斯古德伊尔机场"},
        "MZJ":{name:"Pinal",gj:"gj",airport:"皮纳尔飞机坟场机场"},
        "SXM":{name:"圣马丁",gj:"gj",airport:"朱利安娜公主机场"},
        "RYN":{name:"Ryan Field",gj:"gj",airport:"Ryan Field机场"},
        "DQA":{name:"大庆",gj:"gj",airport:"大庆萨尔图机场"},
        "BUE":{name:"布宜诺斯艾利斯",gj:"gj",airport:"布宜诺斯艾利斯机场"},
        "KCH":{name:"古晋",gj:"gj",airport:"古晋机场"},
        "BKI":{name:"沙巴",gj:"gj",airport:"沙巴机场"},
        "HPN":{name:"维斯特切斯特郡",gj:"gj",airport:"维斯特切斯特郡机场"},
        "MLI":{name:"莫林",gj:"gj",airport:"莫林机场"},
        "LIH":{name:"考爱岛",gj:"gj",airport:"考爱岛机场"},
        "MCI":{name:"堪萨斯城",gj:"gj",airport:"堪萨斯城机场"},
        "DSM":{name:"得梅因",gj:"gj",airport:"得梅因机场"},
        "MCO":{name:"奥兰多",gj:"gj",airport:"奥兰多机场"},
        "MDL":{name:"曼德勒",gj:"gj",airport:"曼德勒机场"},
        "TYO":{name:"东京",gj:"gj",airport:"东京机场"},
        "SPK":{name:"札幌",gj:"gj",airport:"札幌机场"},
        "USM":{name:"苏梅岛",gj:"gj",airport:"苏梅岛机场"},
        "IEV":{name:"基辅",gj:"gj",airport:"基辅机场"},
        "JRS":{name:"耶路撒冷",gj:"gj",airport:"耶路撒冷机场"},
        "ROM":{name:"罗马",gj:"gj",airport:"罗马机场"},
        "SUB":{name:"泗水",gj:"gj",airport:"朱安达泗水机场"},
        "REP":{name:"暹粒",gj:"gj",airport:"暹粒吴哥机场"},
        "CHN":{name:"全州",gj:"gj",airport:"全州机场"},
        "PAR":{name:"巴黎",gj:"gj",airport:"巴黎机场"},
        "MOW":{name:"莫斯科",gj:"gj",airport:"莫斯科机场"},
        "ALY":{name:"亚历山大",gj:"gj",airport:"亚历山大机场"},
        "JXA":{name:"鸡西",gj:"gj",airport:"鸡西兴凯湖机场"},
        "LLF":{name:"永州",gj:"gj",airport:"湖南永州零陵机场"},
        "HSC":{name:"韶关",gj:"gj",airport:"韶关机场"},
        "JGS":{name:"井冈山",gj:"gj",airport:"井冈山机场"},
        "FUG":{name:"阜阳",gj:"gj",airport:"阜阳西关机场"},
        "PUJ":{name:"蓬塔卡纳",gj:"gj",airport:"蓬塔卡纳机场"},
        "ERL":{name:"二连浩特",gj:"gj",airport:"二连浩特赛乌苏国际机场"},
        "GYS":{name:"广元",gj:"gj",airport:"广元机场"},
        "FUO":{name:"佛山",gj:"gj",airport:"佛山沙堤机场"},
        "BVA":{name:"博韦",gj:"gj",airport:"博韦蒂耶机场"},
        "LDS":{name:"伊春",gj:"gj",airport:"伊春林都机场"},
        "ANK":{name:"安卡拉",gj:"gj",airport:"安卡拉(首都)机场"},
        "TLQ":{name:"吐鲁番",gj:"gj",airport:"吐鲁番交河机场"},
        "GYU":{name:"固原",gj:"gj",airport:"宁夏固原六盘山机场"},
        "KNH":{name:"金门",gj:"gj",airport:"尚义机场"},
        "MZG":{name:"马公",gj:"gj",airport:"马公机场"},
        "OSS":{name:"奥什",gj:"gj",airport:"奥什机场"},
        "ADY":{name:"奥尔代斯",gj:"gj",airport:"奥尔代斯机场"},
        "YNG":{name:"扬斯顿",gj:"gj",airport:"扬斯顿机场"},
        "RMQ":{name:"台中",gj:"gj",airport:"台中清泉岗机场"},
        "PIF":{name:"屏东",gj:"gj",airport:"屏东机场"},
        "HCN":{name:"恒春",gj:"gj",airport:"恒春五里亭机场"},
        "XNT":{name:"邢台",gj:"gj",airport:"邢台褡裢机场"},
        "XEN":{name:"兴城",gj:"gj",airport:"兴城机场"},
        "AYN":{name:"安阳",gj:"gj",airport:"安阳北郊机场"},
        "MFK":{name:"北竿",gj:"gj",airport:"北竿机场"},
        "LZN":{name:"连江",gj:"gj",airport:"南竿机场"},
        "CMJ":{name:"七美",gj:"gj",airport:"七美机场"},
        "DHN":{name:"多森",gj:"gj",airport:"多森机场"},
        "MSL":{name:"阿拉巴马",gj:"gj",airport:"阿拉巴马西北机场"},
        "BSL":{name:"巴塞尔",gj:"gj",airport:"巴塞尔米卢斯弗赖堡机场"},
        "SXB":{name:"斯特拉斯堡",gj:"gj",airport:"斯特拉斯堡机场"},
        "MWX":{name:"木浦",gj:"gj",airport:"务安机场"},
        "REC":{name:"累西腓",gj:"gj",airport:"累西腓瓜拉拉皮斯吉尔贝托·弗雷雷机场"},
        "MAO":{name:"马瑙斯",gj:"gj",airport:"马瑙斯爱德华多·戈梅斯机场"},
        "SSA":{name:"萨尔瓦多",gj:"gj",airport:"萨尔瓦多路易斯·爱德华多·马加良斯议员机场"},
        "PNJ":{name:"蓬莱",gj:"gj",airport:"蓬莱沙河口机场"},
        "KDH":{name:"坎大哈",gj:"gj",airport:"坎大哈机场"},
        "USH":{name:"乌斯怀亚",gj:"gj",airport:"乌斯怀亚 马尔维纳斯机场"},
        "EZE":{name:"布宜诺斯艾利斯",gj:"gj",airport:"埃塞萨皮斯塔里尼部长机场"},
        "LGG":{name:"列日",gj:"gj",airport:"列日机场"},
        "CRL":{name:"沙尔勒鲁瓦",gj:"gj",airport:"沙尔勒鲁瓦 南布鲁塞尔机场"},
        "TRV":{name:"特里凡得琅",gj:"gj",airport:"特里凡得琅机场"},
        "NAG":{name:"那格浦尔",gj:"gj",airport:"索内格翁机场"},
        "AMD":{name:"艾哈迈达巴德",gj:"gj",airport:"萨达尔·瓦拉巴伊·帕特尔机场"},
        "HKD":{name:"函馆",gj:"gj",airport:"函馆机场"},
        "TAK":{name:"高松",gj:"gj",airport:"高松机场"},
        "KUH":{name:"钏路",gj:"gj",airport:"钏路机场"},
        "MYJ":{name:"松山",gj:"gj",airport:"日本松山机场"},
        "KKJ":{name:"福冈",gj:"gj",airport:"北九州机场"},
        "KMJ":{name:"熊本",gj:"gj",airport:"熊本机场"},
        "OIT":{name:"大分",gj:"gj",airport:"大分机场"},
        "AKJ":{name:"旭川",gj:"gj",airport:"旭川机场"},
        "OBO":{name:"带广",gj:"gj",airport:"带广机场"},
        "AXT":{name:"秋田",gj:"gj",airport:"秋田机场"},
        "UBJ":{name:"山口",gj:"gj",airport:"山口机场"},
        "UTH":{name:"乌隆他尼",gj:"gj",airport:"乌隆他尼机场"},
        "UTP":{name:"芭堤雅",gj:"gj",airport:"乌打抛机场"},
        "HDY":{name:"合艾",gj:"gj",airport:"合艾机场"},
        "SAW":{name:"伊斯坦布尔",gj:"gj",airport:"萨比哈·格克琴机场"},
        "DMM":{name:"达曼",gj:"gj",airport:"法赫德国王机场"},
        "MED":{name:"麦地那",gj:"gj",airport:"穆罕默德·本·阿卜杜勒-阿齐兹亲王机场"},
        "MBD":{name:"姆马巴托",gj:"gj",airport:"姆马巴托机场"},
        "TFN":{name:"特内里费",gj:"gj",airport:"北特内里费机场"},
        "LYR":{name:"斯瓦尔巴群岛",gj:"gj",airport:"斯瓦尔巴朗伊尔机场"},
        "SZG":{name:"萨尔茨堡",gj:"gj",airport:"萨尔茨堡机场"},
        "YXY":{name:"怀特霍斯",gj:"gj",airport:"埃里克·尼尔森怀特霍斯机场"},
        "YHM":{name:"哈密尔顿",gj:"gj",airport:"约翰·卡尔·芒罗哈密尔顿机场"},
        "YKZ":{name:"万锦",gj:"gj",airport:"巴顿维尔机场"},
        "SGD":{name:"森讷堡",gj:"gj",airport:"森讷堡机场"},
        "CNL":{name:"辛代尔",gj:"gj",airport:"辛代尔机场"},
        "ATZ":{name:"艾斯尤特",gj:"gj",airport:"艾斯尤特机场"},
        "LXR":{name:"卢克索",gj:"gj",airport:"卢克索机场"},
        "SSH":{name:"沙姆沙伊赫",gj:"gj",airport:"沙姆沙伊赫机场"},
        "HRG":{name:"古尔代盖",gj:"gj",airport:"古尔代盖机场"},
        "KEF":{name:"凯夫拉维克",gj:"gj",airport:"凯夫拉维克机场"},
        "MDC":{name:"万鸦老",gj:"gj",airport:"美娜多机场"},
        "MHD":{name:"马什哈德",gj:"gj",airport:"马什哈德机场"},
        "SYZ":{name:"设拉子",gj:"gj",airport:"设拉子机场"},
        "CTA":{name:"卡塔尼亚",gj:"gj",airport:"丰坦罗撒机场"},
        "BEN":{name:"班加西",gj:"gj",airport:"班加西贝尼纳机场"},
        "EBJ":{name:"埃斯比约",gj:"gj",airport:"埃斯比约机场"},
        "NGQ":{name:"阿里",gj:"gj",airport:"阿里昆莎机场"},
        "SFB":{name:"奥兰多",gj:"gj",airport:"奥兰多桑福德机场"},
        "DCA":{name:"华盛顿",gj:"gj",airport:"罗纳德·里根机场"},
        "YAD":{name:"麋鹿湖",gj:"gj",airport:"麋鹿湖机场"},
        "YGL":{name:"拉格兰德",gj:"gj",airport:"拉格兰德机场"},
        "YBB":{name:"佩利湾",gj:"gj",airport:"佩利湾机场"},
        "YBD":{name:"新威斯敏斯特",gj:"gj",airport:"新威斯敏斯特机场"},
        "YBN":{name:"博登",gj:"gj",airport:"博登直升机机场"},
        "BHS":{name:"巴瑟斯特",gj:"gj",airport:"巴瑟斯特机场"},
        "MPH":{name:"卡地克兰",gj:"gj",airport:"卡地克兰机场"},
        "ZGI":{name:"神河",gj:"gj",airport:"神河机场"},
        "YSB":{name:"萨德伯里",gj:"gj",airport:"萨德伯里机场"},
        "YYB":{name:"北湾",gj:"gj",airport:"北湾机场"},
        "YKF":{name:"基奇纳",gj:"gj",airport:"基奇纳机场"},
        "TVS":{name:"唐山",gj:"gj",airport:"唐山三女河机场"},
        "GHA":{name:"盖尔达耶",gj:"gj",airport:"盖尔达耶机场"},
        "TGR":{name:"图古尔特",gj:"gj",airport:"图古尔特机场"},
        "ELU":{name:"瓦德",gj:"gj",airport:"盖马尔机场"},
        "FSZ":{name:"牧之原",gj:"gj",airport:"静冈机场"},
        "HIA":{name:"淮安",gj:"gj",airport:"淮安涟水机场"},
        "BPN":{name:"巴厘巴板",gj:"gj",airport:"巴厘巴板机场"},
        "AOC":{name:"莱比锡",gj:"gj",airport:"莱比锡阿尔滕堡机场"},
        "CSO":{name:"马德堡",gj:"gj",airport:"马德堡科赫施泰特机场"},
        "ERF":{name:"艾福特",gj:"gj",airport:"艾福特机场"},
        "SCN":{name:"萨尔布鲁根",gj:"gj",airport:"萨尔布吕肯机场"},
        "QEF":{name:"埃格尔斯巴赫",gj:"gj",airport:"埃格尔斯巴赫机场"},
        "HHN":{name:"法兰克福",gj:"gj",airport:"法兰克福哈恩机场"},
        "MHG":{name:"曼海姆",gj:"gj",airport:"曼海姆市机场"},
        "SGE":{name:"布尔巴赫",gj:"gj",airport:"Siegerland机场"},
        "XFW":{name:"汉堡",gj:"gj",airport:"Hamburg Finkenwerder机场"},
        "GWT":{name:"叙尔特岛",gj:"gj",airport:"叙尔特岛机场"},
        "AES":{name:"奥勒松",gj:"gj",airport:"奥勒松机场"},
        "RYG":{name:"Rygge",gj:"gj",airport:"Rygge机场"},
        "HAU":{name:"海于格松",gj:"gj",airport:"海于格松机场"},
        "KRS":{name:"克里斯蒂安桑",gj:"gj",airport:"克里斯蒂安桑机场"},
        "RRS":{name:"勒罗斯",gj:"gj",airport:"Roeros机场"},
        "YYU":{name:"卡普斯卡辛",gj:"gj",airport:"卡普斯卡辛机场"},
        "YZT":{name:"哈迪港",gj:"gj",airport:"波特哈迪机场"},
        "BPL":{name:"博乐",gj:"gj",airport:"新疆博乐机场"},
        "ZFA":{name:"法鲁",gj:"gj",airport:"法鲁机场"},
        "YXR":{name:"厄尔顿",gj:"gj",airport:"厄尔顿机场"},
        "YSD":{name:"萨菲尔德",gj:"gj",airport:"萨菲尔德机场"},
        "YPC":{name:"波拉图克",gj:"gj",airport:"波拉图克机场"},
        "CLY":{name:"卡尔维",gj:"gj",airport:"圣凯瑟琳机场"},
        "YIK":{name:"伊武吉维克",gj:"gj",airport:"伊武吉维克机场"},
        "YWY":{name:"里格利",gj:"gj",airport:"里格利机场"},
        "YKL":{name:"谢弗维尔",gj:"gj",airport:"谢弗维尔机场"},
        "YXN":{name:"惠尔科夫",gj:"gj",airport:"惠尔科夫机场"},
        "USU":{name:"布苏安加",gj:"gj",airport:"布苏安加机场"},
        "YGV":{name:"Havre ST. Pierre",gj:"gj",airport:"Havre ST. Pierre机场"},
        "YNA":{name:"纳塔什昆",gj:"gj",airport:"纳塔什昆机场"},
        "YQV":{name:"约克顿",gj:"gj",airport:"约克顿机场"},
        "YJF":{name:"利亚德堡",gj:"gj",airport:"利亚德堡机场"},
        "YNE":{name:"挪威豪斯",gj:"gj",airport:"挪威豪斯机场"},
        "YET":{name:"埃德森",gj:"gj",airport:"埃德森机场"},
        "YZP":{name:"桑德斯皮特",gj:"gj",airport:"桑德斯皮特机场"},
        "YLC":{name:"Kimmirut",gj:"gj",airport:"今米鲁特机场"},
        "YZW":{name:"茨林",gj:"gj",airport:"茨林机场"},
        "YDP":{name:"奈恩",gj:"gj",airport:"奈恩机场"},
        "YTL":{name:"大特劳特湖",gj:"gj",airport:"大特劳特湖机场"},
        "YPG":{name:"波蒂奇拉普大草原",gj:"gj",airport:"波蒂奇拉普大草原机场"},
        "YMO":{name:"穆瑟尼",gj:"gj",airport:"穆瑟尼机场"},
        "YQZ":{name:"克内尔",gj:"gj",airport:"克内尔机场"},
        "YFR":{name:"福特雷索卢申",gj:"gj",airport:"福特雷索卢申机场"},
        "YMN":{name:"马库维克",gj:"gj",airport:"马库维克机场"},
        "YKG":{name:"派内贝",gj:"gj",airport:"派内贝机场"},
        "YDN":{name:"多芬",gj:"gj",airport:"多芬机场"},
        "ZUM":{name:"丘吉尔",gj:"gj",airport:"丘吉尔瀑布机场"},
        "ZST":{name:"斯图尔特",gj:"gj",airport:"斯图尔特机场"},
        "WPC":{name:"平彻克里克",gj:"gj",airport:"平彻克里克机场"},
        "ZMT":{name:"马塞特",gj:"gj",airport:"马塞特机场"},
        "YTQ":{name:"Tasiujaq",gj:"gj",airport:"Tasiujaq机场"},
        "YTH":{name:"汤普森",gj:"gj",airport:"汤普森机场"},
        "YQL":{name:"莱斯布里奇",gj:"gj",airport:"莱斯布里奇郡立机场"},
        "YQK":{name:"凯诺拉",gj:"gj",airport:"凯诺拉机场"},
        "YUT":{name:"雷普尔斯湾",gj:"gj",airport:"雷普尔斯湾机场"},
        "YUX":{name:"霍尔海滩",gj:"gj",airport:"霍尔海滩机场"},
        "YWL":{name:"威廉斯湖",gj:"gj",airport:"威廉斯湖机场"},
        "YXC":{name:"克兰布鲁克",gj:"gj",airport:"克兰布鲁克卡纳迪丁罗基斯机场"},
        "YXH":{name:"梅迪辛哈特",gj:"gj",airport:"梅迪辛哈特机场"},
        "YXL":{name:"苏卢考特",gj:"gj",airport:"苏卢考特机场"},
        "YRL":{name:"安大略",gj:"gj",airport:"安大略红湖机场"},
        "YPA":{name:"艾伯特王子城",gj:"gj",airport:"艾伯特王子城机场"},
        "YPE":{name:"和平河",gj:"gj",airport:"和平河机场"},
        "YPL":{name:"皮克尔",gj:"gj",airport:"皮克尔机场"},
        "YPQ":{name:"彼得博勒",gj:"gj",airport:"彼得博勒机场"},
        "YPW":{name:"鲍威尔河",gj:"gj",airport:"鲍威尔河机场"},
        "YPX":{name:"Povungnituk",gj:"gj",airport:"Povungnituk机场"},
        "YPY":{name:"福特奇佩恩",gj:"gj",airport:"福特奇佩恩机场"},
        "YZU":{name:"怀特科特",gj:"gj",airport:"怀特科特机场"},
        "YVO":{name:"瓦勒多",gj:"gj",airport:"瓦勒多机场"},
        "YOD":{name:"冷湖",gj:"gj",airport:"冷湖空军基地机场"},
        "YOA":{name:"卡蒂",gj:"gj",airport:"卡蒂机场"},
        "YHD":{name:"德赖登",gj:"gj",airport:"德赖登机场"},
        "YHE":{name:"霍普",gj:"gj",airport:"霍普机场"},
        "ZBF":{name:"巴瑟斯特",gj:"gj",airport:"加拿大巴瑟斯特机场"},
        "YZS":{name:"科勒尔港",gj:"gj",airport:"科勒尔港机场"},
        "YZH":{name:"艾伯塔",gj:"gj",airport:"艾伯塔奴湖机场"},
        "YZF":{name:"耶洛奈夫",gj:"gj",airport:"耶洛奈夫机场"},
        "YYY":{name:"蒙若利",gj:"gj",airport:"蒙若利机场"},
        "YUB":{name:"塔克托亚图克",gj:"gj",airport:"塔克托亚图克机场"},
        "YTS":{name:"蒂明斯",gj:"gj",airport:"蒂明斯机场"},
        "AAF":{name:"阿帕拉契科拉",gj:"gj",airport:"阿帕拉契科拉机场"},
        "ABI":{name:"阿比林",gj:"gj",airport:"阿比林机场"},
        "ABQ":{name:"伯纳利欧",gj:"gj",airport:"阿尔伯克基机场"},
        "ABR":{name:"布朗",gj:"gj",airport:"美国阿伯丁机场"},
        "ACK":{name:"楠塔基特",gj:"gj",airport:"楠塔基特机场"},
        "ACT":{name:"瓦科",gj:"gj",airport:"瓦科地区机场"},
        "ACV":{name:"加利福尼亚州",gj:"gj",airport:"阿克塔机场"},
        "ACY":{name:"波姆那",gj:"gj",airport:"大西洋城机场"},
        "AFW":{name:"塔兰特",gj:"gj",airport:"Fort Worth Alliance机场"},
        "ALI":{name:"艾丽斯",gj:"gj",airport:"艾丽斯机场"},
        "ALN":{name:"奥尔顿",gj:"gj",airport:"奥尔顿机场"},
        "ALO":{name:"滑铁卢",gj:"gj",airport:"滑铁卢地区机场"},
        "ALW":{name:"瓦拉瓦拉",gj:"gj",airport:"瓦拉瓦拉机场"},
        "AMA":{name:"阿马里洛",gj:"gj",airport:"阿马里洛机场"},
        "ANB":{name:"安妮斯顿",gj:"gj",airport:"安妮斯顿梅特勒波利滕机场"},
        "AND":{name:"安德森",gj:"gj",airport:"安德森机场"},
        "APN":{name:"阿尔皮纳",gj:"gj",airport:"阿尔皮纳机场"},
        "ART":{name:"沃特敦",gj:"gj",airport:"沃特敦机场"},
        "ATY":{name:"沃特敦",gj:"gj",airport:"沃特敦地区机场"},
        "AVL":{name:"阿什维尔",gj:"gj",airport:"阿什维尔机场"},
        "AVP":{name:"Pittston Township",gj:"gj",airport:"威尔克斯-巴里机场"},
        "AXN":{name:"亚历山德里亚",gj:"gj",airport:"亚历山德里亚机场"},
        "AZO":{name:"卡拉马祖",gj:"gj",airport:"卡拉马祖/巴特尔克里克机场"},
        "BDE":{name:"伍兹湖县",gj:"gj",airport:"巴德特BAUDETTE机场"},
        "BDR":{name:"布里奇波特",gj:"gj",airport:"布里奇波特机场"},
        "BFD":{name:"布拉德福德",gj:"gj",airport:"布拉德福德机场"},
        "BFI":{name:"西雅图",gj:"gj",airport:"波音场国王郡立机场"},
        "BFL":{name:"贝克斯菲尔德",gj:"gj",airport:"梅多斯场机场"},
        "BGM":{name:"缅因",gj:"gj",airport:"Greater Binghamton机场"},
        "BGR":{name:"班戈",gj:"gj",airport:"班戈机场"},
        "BIL":{name:"比林斯",gj:"gj",airport:"比林斯机场"},
        "BIS":{name:"俾斯麦",gj:"gj",airport:"俾斯麦机场"},
        "BJC":{name:"杰弗科",gj:"gj",airport:"杰弗科机场"},
        "BKE":{name:"贝克县",gj:"gj",airport:"贝克机场"},
        "BKL":{name:"克利夫兰",gj:"gj",airport:"克利夫兰伯克莱克夫兰特机场"},
        "BLI":{name:"贝灵汉",gj:"gj",airport:"贝灵汉机场"},
        "BRL":{name:"柏林顿",gj:"gj",airport:"伯灵顿机场"},
        "BRO":{name:"布朗斯维尔",gj:"gj",airport:"布朗斯维尔南帕德雷岛机场"},
        "BTM":{name:"比尤特",gj:"gj",airport:"比尤特贝尔穆尼机场"},
        "BTL":{name:"卡尔霍恩",gj:"gj",airport:"WK凯洛格机场"},
        "BVY":{name:"埃塞克斯",gj:"gj",airport:"贝弗利机场"},
        "CAK":{name:"斯塔克",gj:"gj",airport:"阿克伦坎顿机场"},
        "CDC":{name:"锡达城",gj:"gj",airport:"锡达城机场"},
        "CEF":{name:"斯普林菲尔德",gj:"gj",airport:"韦斯托弗机场"},
        "CEW":{name:"克雷斯特维",gj:"gj",airport:"鲍勃赛克斯机场"},
        "CGI":{name:"开普吉拉多",gj:"gj",airport:"开普吉拉多机场"},
        "CHA":{name:"查塔努加",gj:"gj",airport:"Lovell Field机场"},
        "CHO":{name:"夏洛茨维尔",gj:"gj",airport:"夏洛茨维尔阿尔伯马尔机场"},
        "CID":{name:"锡达拉皮兹",gj:"gj",airport:"锡达拉皮兹机场"},
        "CIU":{name:"密歇根",gj:"gj",airport:"奇普瓦郡立机场"},
        "CKB":{name:"布里奇波特",gj:"gj",airport:"North Central West Virginia机场"},
        "CLM":{name:"安吉利斯港",gj:"gj",airport:"William R. Fairchild机场"},
        "YFC":{name:"弗雷德里克顿",gj:"gj",airport:"弗雷德里克顿机场"},
        "MSO":{name:"米苏拉",gj:"gj",airport:"米苏拉机场"},
        "MSS":{name:"马塞纳",gj:"gj",airport:"马塞纳机场"},
        "MWH":{name:"Moses Lake",gj:"gj",airport:"格兰特郡立机场"},
        "MYR":{name:"默特尔比奇",gj:"gj",airport:"默特尔比奇机场"},
        "IBR":{name:"茨城",gj:"gj",airport:"茨城机场"},
        "GCI":{name:"格恩济",gj:"gj",airport:"格恩济机场"},
        "ESH":{name:"肖勒姆",gj:"gj",airport:"肖勒姆由海机场"},
        "GLO":{name:"格洛斯特",gj:"gj",airport:"格洛斯特机场"},
        "CAL":{name:"坎贝尔镇",gj:"gj",airport:"坎贝尔镇机场"},
        "CWL":{name:"加的夫",gj:"gj",airport:"加的夫机场"},
        "BRS":{name:"布里斯托尔",gj:"gj",airport:"布里斯托尔机场"},
        "LTN":{name:"伦敦",gj:"gj",airport:"伦敦卢顿机场"},
        "ROS":{name:"罗萨里奥",gj:"gj",airport:"罗萨里奥机场"},
        "YGP":{name:"加斯佩",gj:"gj",airport:"加斯佩机场"},
        "YGQ":{name:"杰拉尔顿",gj:"gj",airport:"杰拉尔顿机场"},
        "YGR":{name:"麦迪兰群岛",gj:"gj",airport:"麦迪兰群岛机场"},
        "YGT":{name:"伊格卢利克",gj:"gj",airport:"伊格卢利克机场"},
        "YGW":{name:"库朱阿拉普",gj:"gj",airport:"库朱阿拉普机场"},
        "YGX":{name:"古拉木",gj:"gj",airport:"古拉木机场"},
        "YMJ":{name:"穆斯乔",gj:"gj",airport:"穆斯乔机场"},
        "YMT":{name:"祺布嘎莫",gj:"gj",airport:"祺布嘎莫机场"},
        "YXD":{name:"埃德蒙顿",gj:"gj",airport:"埃德蒙顿市中心机场"},
        "SOU":{name:"南安普敦",gj:"gj",airport:"南安普敦机场"},
        "STN":{name:"伦敦",gj:"gj",airport:"伦敦斯坦斯特德机场"},
        "ELG":{name:"埃尔果累阿",gj:"gj",airport:"埃尔果累阿机场"},
        "HME":{name:"哈西迈萨乌德",gj:"gj",airport:"哈西迈萨乌德机场"},
        "INZ":{name:"因萨拉赫",gj:"gj",airport:"因萨拉赫机场"},
        "LOO":{name:"艾格瓦特",gj:"gj",airport:"艾格瓦特机场"},
        "TMX":{name:"提米蒙",gj:"gj",airport:"提米蒙机场"},
        "BOY":{name:"博博迪乌拉索",gj:"gj",airport:"BOBO DIOULASSO机场"},
        "KMS":{name:"库马西",gj:"gj",airport:"库马西机场"},
        "ABV":{name:"阿布贾",gj:"gj",airport:"阿布贾机场"},
        "TEE":{name:"泰贝萨",gj:"gj",airport:"泰贝萨机场"},
        "CZL":{name:"康斯坦丁",gj:"gj",airport:"CONSTANTINE MOHAMED BOUDIAF机场"},
        "AAE":{name:"安纳巴",gj:"gj",airport:"安纳巴机场"},
        "IAM":{name:"因阿迈纳斯",gj:"gj",airport:"因阿迈纳斯机场"},
        "ZAR":{name:"扎里亚",gj:"gj",airport:"扎里亚机场"},
        "MFQ":{name:"马拉迪",gj:"gj",airport:"马拉迪机场"},
        "AJY":{name:"阿加德兹",gj:"gj",airport:"阿加德兹机场"},
        "ZND":{name:"津德尔",gj:"gj",airport:"津德尔机场"},
        "TBJ":{name:"塔巴卡",gj:"gj",airport:"塔巴卡机场"},
        "MIR":{name:"莫纳斯提尔",gj:"gj",airport:"莫纳斯提尔机场"},
        "GAF":{name:"加夫萨",gj:"gj",airport:"加夫萨机场"},
        "GAE":{name:"加贝斯",gj:"gj",airport:"加贝斯机场"},
        "DJE":{name:"杰尔巴",gj:"gj",airport:"梅利塔机场"},
        "SFA":{name:"斯法克斯",gj:"gj",airport:"斯法克斯Thyna机场"},
        "TOE":{name:"托泽尔",gj:"gj",airport:"托泽尔机场"},
        "OST":{name:"奥斯坦德",gj:"gj",airport:"奥斯坦德机场"},
        "HDF":{name:"赫林斯多夫",gj:"gj",airport:"赫林斯多夫机场"},
        "FMO":{name:"蒙斯特",gj:"gj",airport:"蒙斯特机场"},
        "KEL":{name:"基尔",gj:"gj",airport:"基尔机场"},
        "UUD":{name:"ULAN-UDE",gj:"gj",airport:"ULAN-UDE机场"},
        "ARH":{name:"阿尔汉格尔斯克",gj:"gj",airport:"阿尔汉格尔斯克机场"},
        "AMV":{name:"AMDERMA",gj:"gj",airport:"AMDERMA机场"},
        "MMK":{name:"摩尔曼斯科",gj:"gj",airport:"摩尔曼斯科机场"},
        "TGG":{name:"瓜拉丁加奴",gj:"gj",airport:"瓜拉丁加奴机场"},
        "ORN":{name:"奥兰",gj:"gj",airport:"艾塞尼亚机场"},
        "TLM":{name:"特莱姆森",gj:"gj",airport:"特莱姆森机场"},
        "TIN":{name:"廷杜夫",gj:"gj",airport:"廷杜夫机场"},
        "TID":{name:"提亚雷特",gj:"gj",airport:"提亚雷特机场"},
        "INF":{name:"因盖扎姆",gj:"gj",airport:"因盖扎姆机场"},
        "ANF":{name:"安托法加斯塔",gj:"gj",airport:"CERRO MORENO机场"},
        "LSQ":{name:"洛斯安赫莱斯",gj:"gj",airport:"洛斯安赫莱斯机场"},
        "YLD":{name:"沙普洛",gj:"gj",airport:"沙普洛机场"},
        "YLJ":{name:"梅多莱克",gj:"gj",airport:"梅多莱克机场"},
        "YLL":{name:"劳埃德明斯特",gj:"gj",airport:"劳埃德明斯特机场"},
        "YLT":{name:"艾乐特",gj:"gj",airport:"艾乐特机场"},
        "XGR":{name:"坎吉克斯瓦尔",gj:"gj",airport:"坎吉克斯瓦尔机场"},
        "YMM":{name:"马克马里堡",gj:"gj",airport:"马克马里堡机场"},
        "YUD":{name:"乌苗奥",gj:"gj",airport:"乌苗奥机场"},
        "YMX":{name:"蒙特利尔",gj:"gj",airport:"米拉贝尔机场"},
        "YNC":{name:"韦明吉",gj:"gj",airport:"韦明吉机场"},
        "YND":{name:"加蒂诺",gj:"gj",airport:"加蒂诺机场"},
        "YZX":{name:"格林伍德",gj:"gj",airport:"格林伍德机场"},
        "YZV":{name:"七岛港",gj:"gj",airport:"七岛港机场"},
        "YYR":{name:"古斯贝",gj:"gj",airport:"古斯贝机场"},
        "YYN":{name:"斯威夫特卡伦特",gj:"gj",airport:"斯威夫特卡伦特机场"},
        "YYH":{name:"TALOYOAK",gj:"gj",airport:"TALOYOAK机场"},
        "YYE":{name:"纳尔逊堡",gj:"gj",airport:"纳尔逊堡机场"},
        "YYD":{name:"史密瑟斯",gj:"gj",airport:"史密瑟斯机场"},
        "YXZ":{name:"沃瓦",gj:"gj",airport:"沃瓦机场"},
        "YXX":{name:"阿伯兹福德",gj:"gj",airport:"阿伯兹福德机场"},
        "BGO":{name:"卑尔根",gj:"gj",airport:"卑尔根机场"},
        "KJA":{name:"克拉斯诺亚尔斯克",gj:"gj",airport:"克拉斯诺亚尔斯克机场"},
        "CPE":{name:"坎佩切",gj:"gj",airport:"坎佩切机场"},
        "CJS":{name:"华雷斯",gj:"gj",airport:"华雷斯机场"},
        "CZA":{name:"奇琴伊查",gj:"gj",airport:"奇琴伊查机场"},
        "CVM":{name:"维多利亚城",gj:"gj",airport:"维多利亚城机场"},
        "CRK":{name:"克拉克",gj:"gj",airport:"克拉克机场"},
        "POP":{name:"普拉塔港",gj:"gj",airport:"Puerto PLata Gregorio Luperon机场"},
        "STI":{name:"圣地亚哥",gj:"gj",airport:"SANTIAGO MUNICIPAL机场"},
        "MBJ":{name:"蒙特哥贝",gj:"gj",airport:"SANGSTER机场"},
        "HUX":{name:"HUATULCO",gj:"gj",airport:"HUATULCO机场"},
        "CVJ":{name:"魁那伐克",gj:"gj",airport:"魁那伐克机场"},
        "CME":{name:"卡门城",gj:"gj",airport:"卡门城机场"},
        "CTM":{name:"切图马尔",gj:"gj",airport:"切图马尔机场"},
        "CLQ":{name:"科利马",gj:"gj",airport:"科利马机场"},
        "ISG":{name:"冲绳",gj:"gj",airport:"石垣机场"},
        "BRX":{name:"巴拉奥纳",gj:"gj",airport:"巴拉奥纳机场"},
        "LDB":{name:"隆德里纳",gj:"gj",airport:"隆德里纳机场"},
        "XCR":{name:"马恩河畔沙隆",gj:"gj",airport:"瓦特里机场"},
        "HSG":{name:"佐贺",gj:"gj",airport:"佐贺机场"},
        "PAE":{name:"埃弗里特",gj:"gj",airport:"埃弗雷特潘恩机场"},
        "PKC":{name:"彼得罗巴甫洛夫斯克",gj:"gj",airport:"彼得罗巴甫洛夫斯克机场"},
        "KGF":{name:"卡拉干达",gj:"gj",airport:"卡拉干达机场"},
        "PWE":{name:"佩韦克",gj:"gj",airport:"佩韦克机场"},
        "PKV":{name:"普斯科夫",gj:"gj",airport:"普斯科夫机场"},
        "VGD":{name:"沃洛格达",gj:"gj",airport:"沃洛格达机场"},
        "BQT":{name:"布雷斯特",gj:"gj",airport:"布雷斯特机场"},
        "GME":{name:"戈梅尔",gj:"gj",airport:"戈梅尔机场"},
        "VTB":{name:"维捷布斯克",gj:"gj",airport:"维捷布斯克机场"},
        "KGD":{name:"加里宁格勒",gj:"gj",airport:"加里宁格勒机场"},
        "GNA":{name:"格罗德诺",gj:"gj",airport:"格罗德诺机场"},
        "GYD":{name:"巴库",gj:"gj",airport:"巴库比纳机场"},
        "EGO":{name:"别尔哥罗德",gj:"gj",airport:"别尔哥罗德机场"},
        "VOZ":{name:"沃罗涅什",gj:"gj",airport:"沃罗涅什机场"},
        "UCT":{name:"乌赫塔",gj:"gj",airport:"乌赫塔机场"},
        "USK":{name:"乌辛斯克",gj:"gj",airport:"乌辛斯克机场"},
        "VKT":{name:"沃尔库塔",gj:"gj",airport:"沃尔库塔机场"},
        "TIJ":{name:"蒂华纳",gj:"gj",airport:"蒂华纳-罗德里格斯机场"},
        "TRH":{name:"特罗纳",gj:"gj",airport:"特罗纳机场"},
        "HHQ":{name:"华欣",gj:"gj",airport:"华欣机场"},
        "NTL":{name:"纽卡斯尔",gj:"gj",airport:"威廉斯敦机场"},
        "YEG":{name:"埃德蒙顿",gj:"gj",airport:"埃德蒙顿机场"},
        "NLK":{name:"诺福克岛",gj:"gj",airport:"诺福克岛机场"},
        "DBO":{name:"达博",gj:"gj",airport:"达博机场"},
        "XCH":{name:"圣诞岛",gj:"gj",airport:"圣诞岛机场"},
        "UMR":{name:"伍默拉",gj:"gj",airport:"伍默拉机场"},
        "KTR":{name:"凯瑟琳",gj:"gj",airport:"廷德尔机场"},
        "PHE":{name:"黑德兰港",gj:"gj",airport:"黑德兰港机场"},
        "LEA":{name:"利尔蒙斯",gj:"gj",airport:"利尔蒙斯机场"},
        "KNX":{name:"库努纳拉",gj:"gj",airport:"库努纳拉机场"},
        "KGI":{name:"卡尔古利",gj:"gj",airport:"卡尔古利机场"},
        "JAD":{name:"詹达科特",gj:"gj",airport:"詹达科特机场"},
        "JHB":{name:"柔佛州",gj:"gj",airport:"士乃机场"},
        "GOV":{name:"戈夫",gj:"gj",airport:"戈夫机场"},
        "CCK":{name:"科科斯岛",gj:"gj",airport:"科科斯岛机场"},
        "LST":{name:"朗塞斯顿",gj:"gj",airport:"朗塞斯顿机场"},
        "HBA":{name:"霍巴特",gj:"gj",airport:"霍巴特机场"},
        "HID":{name:"霍恩岛",gj:"gj",airport:"霍恩岛机场"},
        "GET":{name:"杰拉尔顿",gj:"gj",airport:"杰拉尔敦机场"},
        "FDU":{name:"班顿杜",gj:"gj",airport:"班顿杜机场"},
        "HEH":{name:"海霍",gj:"gj",airport:"茵莱湖机场"},
        "NYU":{name:"良乌",gj:"gj",airport:"良乌机场"},
        "BHK":{name:"布哈拉",gj:"gj",airport:"布哈拉机场"},
        "BME":{name:"布鲁姆",gj:"gj",airport:"布鲁姆机场"},
        "ROK":{name:"罗克汉普顿",gj:"gj",airport:"罗克汉普顿机场"},
        "FBM":{name:"卢本巴希",gj:"gj",airport:"卢本巴希机场"},
        "JIQ":{name:"黔江",gj:"gj",airport:"黔江舟白机场"},
        "CEH":{name:"承德",gj:"gj",airport:"承德机场"},
        "ADB":{name:"伊兹密尔",gj:"gj",airport:"伊兹密尔Adnan Menderes机场"},
        "JKT":{name:"雅加达",gj:"gj",airport:"雅加达机场"},
        "MLM":{name:"莫雷利亚",gj:"gj",airport:"莫雷利亚机场"},
        "CWI":{name:"克林顿县",gj:"gj",airport:"克林顿机场"},
        "DAD":{name:"岘港",gj:"gj",airport:"岘港机场"},
        "AMI":{name:"马塔兰",gj:"gj",airport:"Selaparang机场"},
        "LSY":{name:"利斯莫尔",gj:"gj",airport:"利斯莫尔机场"},
        "YIE":{name:"阿尔山",gj:"gj",airport:"阿尔山伊尔施机场"},
        "TLU":{name:"托卢",gj:"gj",airport:"托卢机场"},
        "APL":{name:"楠普拉",gj:"gj",airport:"楠普拉机场"},
        "PDG":{name:"巴东",gj:"gj",airport:"达滨机场"},
        "RKZ":{name:"日喀则",gj:"gj",airport:"日喀则和平机场"},
        "DUR":{name:"德班",gj:"gj",airport:"德班机场"},
        "LNK":{name:"林肯",gj:"gj",airport:"林肯机场"},
        "DTW":{name:"底特律",gj:"gj",airport:"底特律都会韦恩县机场"},
        "FYV":{name:"费耶特维尔",gj:"gj",airport:"费耶特维尔机场"},
        "ORL":{name:"奥兰多",gj:"gj",airport:"赫登机场"},
        "IGR":{name:"伊瓜苏",gj:"gj",airport:"伊瓜苏机场"},
        "ISP":{name:"纽约",gj:"gj",airport:"长岛机场"},
        "BDL":{name:"哈特福德县",gj:"gj",airport:"哈特福德机场"},
        "MQP":{name:"内尔斯普雷特",gj:"gj",airport:"克鲁格姆普马兰加国际机场机场"},
        "SPU":{name:"斯普利特",gj:"gj",airport:"斯普利特机场机场"},
        "FWA":{name:"韦恩堡",gj:"gj",airport:"韦恩堡巴尔机场"},
        "YUL":{name:"多佛尔",gj:"gj",airport:"蒙特利尔特鲁多机场"},
        "JIC":{name:"金昌",gj:"gj",airport:"金昌机场"},
        "LAO":{name:"拉瓦格",gj:"gj",airport:"拉瓦格机场"},
        "CAG":{name:"卡利亚里",gj:"gj",airport:"卡利亚里机场"},
        "CIA":{name:"罗马",gj:"gj",airport:"罗马钱皮诺机场"},
        "PBH":{name:"帕罗",gj:"gj",airport:"帕罗机场"},
        "KLO":{name:"卡利博",gj:"gj",airport:"卡利博机场"},
        "YZY":{name:"张掖",gj:"gj",airport:"张掖机场"},
        "TWU":{name:"斗湖",gj:"gj",airport:"斗湖机场"},
        "LGP":{name:"黎牙实比",gj:"gj",airport:"黎牙实比机场"},
        "TAG":{name:"塔比拉兰",gj:"gj",airport:"塔比拉兰机场"},
        "ARD":{name:"阿洛岛",gj:"gj",airport:"阿洛岛机场"},
        "KOE":{name:"古邦",gj:"gj",airport:"古邦机场"},
        "ZQN":{name:"皇后镇",gj:"gj",airport:"皇后镇机场"},
        "YTY":{name:"扬州",gj:"gj",airport:"扬州泰州机场"},
        "RLK":{name:"巴彦淖尔",gj:"gj",airport:"巴彦淖尔天吉泰机场"},
        "TOS":{name:"特罗姆瑟",gj:"gj",airport:"特罗姆瑟机场"},
        "LPQ":{name:"朗勃拉邦",gj:"gj",airport:"朗勃拉邦机场"},
        "KMQ":{name:"小松",gj:"gj",airport:"小松机场"},
        "CWB":{name:"库里蒂巴",gj:"gj",airport:"库里蒂巴机场"},
        "LBD":{name:"胡占德",gj:"gj",airport:"胡占德机场"},
        "BQS":{name:"布拉戈维申斯克",gj:"gj",airport:"布拉戈维申斯克机场"},
        "YKS":{name:"雅库茨克",gj:"gj",airport:"雅库茨克机场"},
        "REN":{name:"奥伦堡",gj:"gj",airport:"奥伦堡机场"},
        "NWI":{name:"诺维奇",gj:"gj",airport:"诺维奇机场"},
        "LMQ":{name:"布雷加港",gj:"gj",airport:"布雷加港机场"},
        "BSR":{name:"巴士拉",gj:"gj",airport:"巴士拉机场"},
        "KUA":{name:"关丹",gj:"gj",airport:"关丹机场"},
        "RGA":{name:"里奥格兰德",gj:"gj",airport:"里奥格兰德机场"},
        "CEI":{name:"清来",gj:"gj",airport:"清来机场"},
        "PPS":{name:"普林塞萨港",gj:"gj",airport:"普林塞萨港机场"},
        "URT":{name:"万纶",gj:"gj",airport:"万纶机场"},
        "BIQ":{name:"比亚里茨",gj:"gj",airport:"比亚里茨-安格雷机场"},
        "COK":{name:"科钦",gj:"gj",airport:"科钦机场"},
        "BER":{name:"柏林",gj:"gj",airport:"柏林勃兰登堡机场"},
        "TKU":{name:"图尔库",gj:"gj",airport:"图尔库机场"},
        "TTT":{name:"台东",gj:"gj",airport:"台东丰年机场"},
        "BAM":{name:"巴马科",gj:"gj",airport:"巴马科机场"},
        "SRG":{name:"三宝垄",gj:"gj",airport:"三宝垄艾哈迈德亚尼机场"},
        "NYO":{name:"斯德哥尔摩",gj:"gj",airport:"斯德哥尔摩史卡夫斯塔机场"},
        "BTH":{name:"巴淡岛",gj:"gj",airport:"巴淡岛机场"},
        "TUS":{name:"Tucson",gj:"gj",airport:"图森机场"},
        "KOA":{name:"科纳",gj:"gj",airport:"科纳机场"},
        "SNA":{name:"圣塔安那",gj:"gj",airport:"圣塔安那橙郡县机场"},
        "OGG":{name:"卡胡卢伊",gj:"gj",airport:"卡胡卢伊机场"},
        "KBV":{name:"甲米",gj:"gj",airport:"甲米机场"},
        "AOJ":{name:"青森",gj:"gj",airport:"青森机场"},
        "MSN":{name:"麦迪逊",gj:"gj",airport:"麦迪逊机场"},
        "SGF":{name:"Springfield-Branson National",gj:"gj",airport:"斯普林菲尔德机场"},
        "CIT":{name:"Shimkent",gj:"gj",airport:"什姆肯特机场"},
        "BLQ":{name:"博罗尼亚",gj:"gj",airport:"博罗尼亚机场"},
        "PNQ":{name:"浦那",gj:"gj",airport:"浦那机场"},
        "YNY":{name:"韩国襄阳",gj:"gj",airport:"韩国襄阳机场"},
        "VTZ":{name:"维萨卡帕特南",gj:"gj",airport:"维萨卡帕特南机场"},
        "BZN":{name:"博兹曼",gj:"gj",airport:"博兹曼贝尔格莱德机场"},
        "SZB":{name:"吉隆坡",gj:"gj",airport:"吉隆坡苏丹阿卜杜尔机场"},
        "SUF":{name:"拉默齐亚",gj:"gj",airport:"拉默齐亚机场"},
        "KBR":{name:"哥达巴鲁",gj:"gj",airport:"哥达巴鲁机场"},
        "JAI":{name:"斋浦尔",gj:"gj",airport:"斋浦尔机场"},
        "VNS":{name:"瓦拉纳西",gj:"gj",airport:"瓦拉纳西机场"},
        "PIU":{name:"皮乌拉",gj:"gj",airport:"皮乌拉机场"},
        "JTR":{name:"圣托里尼",gj:"gj",airport:"圣托里尼机场"},
        "DGT":{name:"杜马格特",gj:"gj",airport:"杜马格特机场"},
        "RKV":{name:"雷克亚未克",gj:"gj",airport:"雷克亚未克机场"},
        "JGD":{name:"加格达奇",gj:"gj",airport:"加格达奇机场"},
        "FSD":{name:"苏福尔斯",gj:"gj",airport:"苏福尔斯机场"},
        "BBS":{name:"布莱克布斯",gj:"gj",airport:"布莱克布斯机场"},
        "TOD":{name:"刁曼岛",gj:"gj",airport:"刁曼岛机场"},
        "FAR":{name:"法戈",gj:"gj",airport:"法戈赫克机场"},
        "OMS":{name:"鄂木斯克",gj:"gj",airport:"鄂木斯克机场"},
        "EUG":{name:"尤金",gj:"gj",airport:"尤金机场"},
        "ROA":{name:"罗阿诺克",gj:"gj",airport:"罗阿诺克机场"},
        "CSG":{name:"哥伦布",gj:"gj",airport:"哥伦布机场"},
        "SMF":{name:"萨克拉门托",gj:"gj",airport:"萨克拉门托机场"},
        "FLN":{name:"弗卢里亚诺波利斯",gj:"gj",airport:"弗卢里亚诺波利斯机场"},
        "ADA":{name:"阿达纳",gj:"gj",airport:"阿达纳机场"},
        "EYW":{name:"基韦斯德",gj:"gj",airport:"基韦斯德机场"},
        "ECN":{name:"埃阿坎",gj:"gj",airport:"埃阿坎机场"},
        "EAS":{name:"圣塞瓦斯蒂安",gj:"gj",airport:"圣塞瓦斯蒂安机场"},
        "CNM":{name:"卡尔斯巴德",gj:"gj",airport:"卡尔斯巴德机场"},
        "AEP":{name:"布宜诺斯艾利斯",gj:"gj",airport:"布宜诺斯艾利斯霍尔赫纽贝里机场"},
        "ASE":{name:"阿斯彭",gj:"gj",airport:"阿斯彭机场"},
        "ASR":{name:"开塞利",gj:"gj",airport:"开塞利机场"},
        "ITO":{name:"希洛",gj:"gj",airport:"希洛机场"},
        "KDM":{name:"佳特土",gj:"gj",airport:"佳特土机场"},
        "RAP":{name:"拉皮德城",gj:"gj",airport:"拉皮德城机场"},
        "MRY":{name:"蒙特雷",gj:"gj",airport:"蒙特雷机场"},
        "HNZ":{name:"亨德森",gj:"gj",airport:"亨德森机场"},
        "HUI":{name:"顺化",gj:"gj",airport:"顺化富牌机场"},
        "ELP":{name:"埃尔·帕索",gj:"gj",airport:"埃尔·帕索机场"},
        "PKR":{name:"博卡拉",gj:"gj",airport:"博卡拉机场"},
        "ZTH":{name:"扎金索斯",gj:"gj",airport:"扎金索斯机场"},
        "GNV":{name:"盖恩斯维尔",gj:"gj",airport:"盖恩斯维尔机场"},
        "QRO":{name:"克雷塔罗",gj:"gj",airport:"克雷塔罗机场"},
        "LOP":{name:"海旁",gj:"gj",airport:"海旁机场"},
        "LNY":{name:"拉奈",gj:"gj",airport:"拉奈机场"},
        "TVU":{name:"塔韦乌尼岛",gj:"gj",airport:"塔韦乌尼岛机场"},
        "GDZ":{name:"格连吉克",gj:"gj",airport:"格连吉克机场"},
        "PLU":{name:"贝洛奥里藏特",gj:"gj",airport:"贝洛奥里藏特机场"},
        "CNF":{name:"贝洛奥里藏特",gj:"gj",airport:"坦克雷多内维斯机场"},
        "VRA":{name:"瓦拉德",gj:"gj",airport:"瓦拉德机场"},
        "UDI":{name:"乌贝兰迪亚",gj:"gj",airport:"乌贝兰迪亚机场"},
        "VCP":{name:"圣保罗",gj:"gj",airport:"坎皮纳斯机场"},
        "AJU":{name:"阿拉卡茹",gj:"gj",airport:"阿拉卡茹机场"},
        "MCN":{name:"梅肯",gj:"gj",airport:"梅肯机场"},
        "JUB":{name:"朱巴",gj:"gj",airport:"朱巴机场"},
        "IPC":{name:"复活节岛",gj:"gj",airport:"复活节岛马塔维里机场"},
        "YGJ":{name:"鸟取",gj:"gj",airport:"鸟取机场"},
        "CXR":{name:"芽庄",gj:"gj",airport:"芽庄金兰机场"},
        "EIN":{name:"埃因霍温",gj:"gj",airport:"埃因霍温机场"},
        "DLI":{name:"大叻",gj:"gj",airport:"大叻莲姜机场"},
        "MYY":{name:"美里",gj:"gj",airport:"美里机场"},
        "IGU":{name:"伊瓜苏瀑布",gj:"gj",airport:"伊瓜苏瀑布机场"},
        "RNB":{name:"龙讷比",gj:"gj",airport:"龙讷比机场"},
        "AOR":{name:"亚罗士打",gj:"gj",airport:"AOR机场"},
        "UPG":{name:"乌戎潘当",gj:"gj",airport:"乌戎潘当机场"},
        "VII":{name:"荣市",gj:"gj",airport:"荣市机场"},
        "KRR":{name:"克拉斯诺达",gj:"gj",airport:"克拉斯诺达机场"},
        "IXC":{name:"昌迪加尔",gj:"gj",airport:"昌迪加尔机场"},
        "JOG":{name:"日惹",gj:"gj",airport:"日惹机场"},
        "LUW":{name:"卢武克",gj:"gj",airport:"卢武克机场"},
        "HER":{name:"伊拉克利翁",gj:"gj",airport:"伊拉克利翁机场"}

}

//通过机场三字码获取城市名
AirportCity.getCityName = function(city){
    var tmp = "";
    if(AirportCity[city]){
        tmp = AirportCity[city].name;
    }
    return tmp;
}

//通过城市名获取机场三字码
AirportCity.getNameCity = function(name){
    var tmp = "";
    for(var key in AirportCity){
    	if(AirportCity[key].name == name){
    		tmp = key;
    	}
    }
    return tmp;
}
AirportCity.getInfo=function(arg){
	var info;
	if(typeof(arg.name)!='undefined'){
		for(var key in AirportCity){
			if(AirportCity[key].name == arg.name){
				info=AirportCity[key];
				info.code=key; 
				break;
			}
		}
	}else if(typeof(arg.code)!="undefined"){
		if(AirportCity[arg.code]){
			info=AirportCity[arg.code];
		}
	}
	return info;
}
